Deterministic registration
isl-org/Open3D pull request #3737
Opened 2021-07-14 08:01 UTC by gsakkis

This PR addresses https://github.com/intel-isl/Open3D/issues/1263 for allowing deterministic registration:
- Adds a `seed` optional parameter to `RegistrationRANSACBasedOnCorrespondence` and `RegistrationRANSACBasedOnFeatureMatching`
- Adds a `seed` member to `FastGlobalRegistrationOption`
- Replaces the `UniformRandInt` function with a callable class that accepts an optional seed.

2021-07-19 14:45 UTC, theNded requested changes
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d/3737)* status: all files reviewed, 2 unresolved discussions (waiting on @gsakkis, @ssheorey, and @yxlao)

___
*[cpp/open3d/pipelines/registration/FastGlobalRegistration.h, line 73 at r1](https://reviewable.io/reviews/intel-isl/open3d/3737#-MezCfhh9XaRDwIo-b2G:-MezCfhh9XaRDwIo-b2H:bmn67y3) ([raw file](https://github.com/intel-isl/open3d/blob/10c081951824e76c303217a426bc84e706178823/cpp/open3d/pipelines/registration/FastGlobalRegistration.h#L73)):*
> ```objc
>                                  double tuple_scale = 0.95,
>                                  int maximum_tuple_count = 1000,
>                                  unsigned int seed = std::random_device{}())
> ```

Also use utility::nullopt here for consistency?
___
*[cpp/tests/core/Tensor.cpp, line 1702 at r1](https://reviewable.io/reviews/intel-isl/open3d/3737#-MezDXk2CcJOGpbCZFcT:-MezDXk2CcJOGpbCZFcU:b-bzgf5l) ([raw file](https://github.com/intel-isl/open3d/blob/10c081951824e76c303217a426bc84e706178823/cpp/tests/core/Tensor.cpp#L1702)):*
> ```cpp
>     int64_t max_size = *std::max_element(sizes.begin(), sizes.end());
>     std::vector<int> vals(max_size);
>     utility::UniformRandInt dist_gen(0, 3);
> ```

Potentially add a test in registration to verify that the results are deterministic?


<!-- Sent from Reviewable.io -->

2021-07-26 18:22 UTC, yxlao requested changes

2021-07-26 18:22 UTC, yxlao commented on cpp/open3d/utility/Helper.h
> +class UniformRandInt {
nit: rename to `UniformRandIntGenerator`, since it is a class to generate `int`, it is not an `int` itself.

2021-07-26 18:22 UTC, yxlao commented on cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp
> +    utility::UniformRandInt dist_gen(0, ncorr - 1, seed_val);
nit: rename `dist_gen` to `rand_generator` since the name `dist` is new

2021-07-26 18:22 UTC, yxlao commented on cpp/tests/core/Tensor.cpp
> +                   [&dist_gen](int x) -> int { return dist_gen(); });
nit: since this is one-time use, can we do something like `utility::UniformRandInt(0, 3)()`?

2021-07-26 18:22 UTC, yxlao commented on cpp/open3d/pipelines/registration/FastGlobalRegistration.h
> +#include <random>
Is this needed?

2021-07-27 09:51 UTC, gsakkis commented
Addressed all comments, thanks for the review.

2021-07-28 21:30 UTC, theNded approved these changes
> Reviewed 1 of 6 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3737)* status: all files reviewed, 6 unresolved discussions (waiting on @gsakkis and @ssheorey)



<!-- Sent from Reviewable.io -->

2021-07-31 11:12 UTC, yxlao approved these changes

2021-07-31 11:12 UTC, merged

2023-06-22 07:44 UTC, dalnoguer commented
Hello, it seems that the seed is not exposed in python. Would it be possible to do so?

```
(Pdb) o3d.pipelines.registration.FastGlobalRegistrationOption(maximum_correspondence_distance=distance_threshold, seed=0)
*** TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. open3d.cuda.pybind.pipelines.registration.FastGlobalRegistrationOption(arg0: open3d.cuda.pybind.pipelines.registration.FastGlobalRegistrationOption)
    2. open3d.cuda.pybind.pipelines.registration.FastGlobalRegistrationOption(division_factor: float = 1.4, use_absolute_scale: bool = False, decrease_mu: bool = False, maximum_correspondence_distance: float = 0.025, iteration_number: int = 64, tuple_scale: float = 0.95, maximum_tuple_count: int = 1000, tuple_test: bool = True)

Invoked with: kwargs: maximum_correspondence_distance=0.005, seed=0
```

Thanks!