(not ready for review) cuda static linking
isl-org/Open3D pull request #3817
Opened 2021-07-28 21:15 UTC by yxlao

2021-07-29 12:36 UTC, stotko requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3817)* status: all files reviewed, 4 unresolved discussions (waiting on @benjaminum and @yxlao)

___
*[3rdparty/find_dependencies.cmake, line 1239 at r1](https://reviewable.io/reviews/isl-org/open3d/3817#-MfmDiYQDHbimS-yZrqH:-MfmDiYQDHbimS-yZrqI:bf2l9vz) ([raw file](https://github.com/isl-org/open3d/blob/f9acb58cca757d91c466e75be18f1d1560965c06/3rdparty/find_dependencies.cmake#L1239)):*
> ```CMake
> list(APPEND Open3D_3RDPARTY_PUBLIC_TARGETS Open3D::3rdparty_parallelstl)
> 
> # Faiss: must be linked before cuBLAS if cuBLAS is a static library
> ```

Could you elaborate on why the linker order matters in this case? What is the error if `faiss` is linked after `cuBLAS`?
___
*[3rdparty/find_dependencies.cmake, line 1244 at r1](https://reviewable.io/reviews/isl-org/open3d/3817#-MfmD94iCLodY0RABgOD:-MfmD94iCLodY0RABgOE:b8337q2) ([raw file](https://github.com/isl-org/open3d/blob/f9acb58cca757d91c466e75be18f1d1560965c06/3rdparty/find_dependencies.cmake#L1244)):*
> ```CMake
>     set(WITH_FAISS OFF)
> elseif(WITH_FAISS)
>     message(STATUS "Building third-party library faiss from source")
> ```

We can move these two lines into the `if (WITH_FAISS)` below to simplify the logic.
___
*[3rdparty/find_dependencies.cmake, line 1253 at r1](https://reviewable.io/reviews/isl-org/open3d/3817#-MfmEBNd0ldBftvO4p8f:-MfmEBNd0ldBftvO4p8g:b-ncawwg) ([raw file](https://github.com/isl-org/open3d/blob/f9acb58cca757d91c466e75be18f1d1560965c06/3rdparty/find_dependencies.cmake#L1253)):*
> ```CMake
>         endif()
>     else()
>         set(FAISS_EXTRA_LIBRARIES ${STATIC_MKL_LIBRARIES})
> ```

This variable is empty at this point (when CMake parses the code) and will be defined later.
___
*[3rdparty/find_dependencies.cmake, line 1282 at r1](https://reviewable.io/reviews/isl-org/open3d/3817#-MfmEjZL3_uCa-F-85YF:-MfmEjZL3_uCa-F-85YG:b-lwj39g) ([raw file](https://github.com/isl-org/open3d/blob/f9acb58cca757d91c466e75be18f1d1560965c06/3rdparty/find_dependencies.cmake#L1282)):*
> ```CMake
>             ${LAPACKE_LIBRARIES}
>         )
>         add_library(${PROJECT_NAME}::3rdparty_blas ALIAS 3rdparty_blas)
> ```

`${PROJECT_NAME}::3rdparty_blas` -> `Open3D::3rdparty_blas`.


<!-- Sent from Reviewable.io -->

2021-07-30 08:36 UTC, yxlao reviewed
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3817)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @benjaminum, @junha-l, and @stotko)

___
*[3rdparty/find_dependencies.cmake, line 1239 at r1](https://reviewable.io/reviews/isl-org/open3d/3817#-MfmDiYQDHbimS-yZrqH:-Mfnu1KBCmC7JLt9ljlh:befwndm) ([raw file](https://github.com/isl-org/open3d/blob/f9acb58cca757d91c466e75be18f1d1560965c06/3rdparty/find_dependencies.cmake#L1239)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

Could you elaborate on why the linker order matters in this case? What is the error if `faiss` is linked after `cuBLAS`?
</blockquote></details>

Added comments in CMake. 

There will be missing symbols if we do the inversed order. Typically we need to put the dependency library (cuBLAS) after the library (Faisss) that uses the dependency.
___
*[3rdparty/find_dependencies.cmake, line 1244 at r1](https://reviewable.io/reviews/isl-org/open3d/3817#-MfmD94iCLodY0RABgOD:-Mfnuw575WU9WXmkBjbP:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/f9acb58cca757d91c466e75be18f1d1560965c06/3rdparty/find_dependencies.cmake#L1244)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

We can move these two lines into the `if (WITH_FAISS)` below to simplify the logic.
</blockquote></details>

Done.
___
*[3rdparty/find_dependencies.cmake, line 1253 at r1](https://reviewable.io/reviews/isl-org/open3d/3817#-MfmEBNd0ldBftvO4p8f:-Mfnv46U5jfSfO5WRY2J:b7shhzz) ([raw file](https://github.com/isl-org/open3d/blob/f9acb58cca757d91c466e75be18f1d1560965c06/3rdparty/find_dependencies.cmake#L1253)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

This variable is empty at this point (when CMake parses the code) and will be defined later.
</blockquote></details>

Removed, as Faiss does not need to depend on `FAISS_EXTRA_LIBRARIES`. In fact, after checking Faiss's CMake, Faiss is not using MKL/BLAS library at build time since Faiss is built as a static library.
___
*[3rdparty/find_dependencies.cmake, line 1282 at r1](https://reviewable.io/reviews/isl-org/open3d/3817#-MfmEjZL3_uCa-F-85YF:-MfqYafDCi4N5BkgLyjf:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/f9acb58cca757d91c466e75be18f1d1560965c06/3rdparty/find_dependencies.cmake#L1282)):*
<details><summary><i>Previously, stotko (Patrick Stotko) wrote…</i></summary><blockquote>

`${PROJECT_NAME}::3rdparty_blas` -> `Open3D::3rdparty_blas`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-30 11:49 UTC, stotko approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3817)* status: all files reviewed, 2 unresolved discussions (waiting on @benjaminum, @junha-l, and @yxlao)

___
*[3rdparty/find_dependencies.cmake, line 1276 at r1](https://reviewable.io/reviews/isl-org/open3d/3817#-MfrDlrR3xMZ_GLliTxf:-MfrDlrR3xMZ_GLliTxg:bhdyuh1) ([raw file](https://github.com/isl-org/open3d/blob/f9acb58cca757d91c466e75be18f1d1560965c06/3rdparty/find_dependencies.cmake#L1276)):*
> ```CMake
>         # Open3D. When building with this option, the Python wheel is less
>         # portable as it depends on the external shared libraries.
>         add_library(3rdparty_blas INTERFACE)
> ```

I like this notion of having a universal `3rdparty_blas` target that maps to either OpenBLAS, MKL, etc. It requires to put some `install()` statements in some branches that do not use the automatic `open3d_..._3rdparty_library()` functions, but it allows to move all `list(APPEND Open3D_3RDPARTY_PRIVATE_TARGETS Open3D::3rdparty_blas)` after all that conditional logic in a single place.

Consistency-wise I would prefer above solution, but the current one is also fine as it minimizes the number of changes in this PR.
___
*[3rdparty/find_dependencies.cmake, line 1254 at r2](https://reviewable.io/reviews/isl-org/open3d/3817#-MfrD6av1v44IgkWPVBh:-MfrD6av1v44IgkWPVBi:b-lx27jx) ([raw file](https://github.com/isl-org/open3d/blob/c8821d177139413064c26a3405f5bc27273d6da4/3rdparty/find_dependencies.cmake#L1254)):*
> ```CMake
>         LIBRARIES    ${FAISS_LIBRARIES}
>         LIB_DIR      ${FAISS_LIB_DIR}
>         DEPENDS      ext_faiss ${FAISS_EXTRA_DEPENDENCIES}
> ```

`${FAISS_EXTRA_DEPENDENCIES}` variable has been removed, so we can remove it here as well.


<!-- Sent from Reviewable.io -->

2021-07-30 13:57 UTC, junha-l commented
@yxlao I have confirmed that the previous problems are resolved now on my enviroment
I've installed open3d build_wheel as you shared previous meeting. 
```
(install wheel file from artifacts and install using pip install open3d***.whl)
>>> import open3d as o3d
>>> o3d.core.cuda.is_available()
True
>>> a = o3d.core.Tensor.ones((10,3),device=o3d.core.Device("CUDA:0"))
>>> a
[[1.0 1.0 1.0],
 [1.0 1.0 1.0],
 [1.0 1.0 1.0],
 [1.0 1.0 1.0],
 [1.0 1.0 1.0],
 [1.0 1.0 1.0],
 [1.0 1.0 1.0],
 [1.0 1.0 1.0],
 [1.0 1.0 1.0],
 [1.0 1.0 1.0]]
Tensor[shape={10, 3}, stride={3, 1}, Float32, CUDA:0, 0x7f4912820c00]
>>> nns = o3d.core.nns.NearestNeighborSearch(a)
>>> nns.knn_index()
True
>>> nns.knn_search(a, knn=3)
([[7 6 5],
 [7 6 5],
 [7 6 5],
 [7 6 5],
 [7 6 5],
 [7 6 5],
 [7 6 5],
 [7 6 5],
 [7 6 5],
 [7 6 5]]
Tensor[shape={10, 3}, stride={3, 1}, Int64, CUDA:0, 0x7f4912820a00], [[0.0 0.0 0.0],
 [0.0 0.0 0.0],
 [0.0 0.0 0.0],
 [0.0 0.0 0.0],
 [0.0 0.0 0.0],
 [0.0 0.0 0.0],
 [0.0 0.0 0.0],
 [0.0 0.0 0.0],
 [0.0 0.0 0.0],
 [0.0 0.0 0.0]]
Tensor[shape={10, 3}, stride={3, 1}, Float32, CUDA:0, 0x7f4912820e00])
```

2021-07-30 14:37 UTC, benjaminum requested changes
I think it looks good. I am thinking of a way to check conflicts with multiple cublas libs (static+dynamic).

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3817#-:-Mfrq7Zm275gj5AUV80j:b-y2890j)* status: all files reviewed, 2 unresolved discussions (waiting on @junha-l and @yxlao)



<!-- Sent from Reviewable.io -->

2021-08-01 07:34 UTC, benjaminum approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3817#-:-Mg-cdP86qOCjIagKqy7:bnfp4nl)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @junha-l, @stotko, and @yxlao)



<!-- Sent from Reviewable.io -->

2021-08-01 09:40 UTC, merged