NPZ support for PointCloud IO
isl-org/Open3D pull request #3851
Opened 2021-08-02 14:10 UTC by reyanshsolis

Changes:
- Added `.npz` support for `tensor pointcloud io`. [No restriction on length shape and type of attribute].
- Added Unit Test.
- Added proxy support in `legacy pointcloud io`, to support `.npz` pointcloud file in current `Open3DViewer`. 
![Screenshot from 2021-08-02 19-33-18](https://user-images.githubusercontent.com/32535717/127874998-aa3507b7-235d-405b-9b7c-276978956aa3.png)

2021-08-03 00:18 UTC, yxlao requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3851)* status: all files reviewed, 2 unresolved discussions (waiting on @reyanshsolis)

___
*[cpp/open3d/io/PointCloudIO.h, line 190 at r1](https://reviewable.io/reviews/isl-org/open3d/3851#-Mg8MFde9lVyqrkzL6FV:-Mg8MFde9lVyqrkzL6FW:b6pjfyf) ([raw file](https://github.com/isl-org/open3d/blob/5f1767752537251408e3b2aa829d4cbae1780e56/cpp/open3d/io/PointCloudIO.h#L190)):*
> ```objc
>                           const WritePointCloudOption &params);
> 
> bool ReadPointCloudFromNPZ(const std::string &filename,
> ```

Is this needed for the visualizer? If not, we can just drop it.
___
*[cpp/open3d/t/io/PointCloudIO.cpp, line 183 at r1](https://reviewable.io/reviews/isl-org/open3d/3851#-Mg8Mbz0DI1UFoWhn0cm:-Mg8Mbz0DI1UFoWhn0cn:b-2uro2r) ([raw file](https://github.com/isl-org/open3d/blob/5f1767752537251408e3b2aa829d4cbae1780e56/cpp/open3d/t/io/PointCloudIO.cpp#L183)):*
> ```cpp
>                            const ReadPointCloudOption &params) {
>     // Required checks are performed in the pointcloud constructor itself.
>     t::geometry::PointCloud pcd(ReadNpz(filename));
> ```

Does it work, if you do
```cpp
pointcloud = t::geometry::PointCloud(ReadNpz(filename));
```


<!-- Sent from Reviewable.io -->

2021-08-04 08:29 UTC, reyanshsolis commented
> Is this needed for the visualizer? If not, we can just drop it.

- Since our `Open3DViewer` uses `legacy geometry` for now if we want to support `.npz` in our current visualizer we may either support `.npz` in `legacy io` or check for extension locally in visualizer code to move this function there (I think, that will make the code more confusing). 

- We can also either drop this support for now and wait for the visualizer to move to `tensor based geometry` or keep it for now, and remove it then.

2021-08-05 02:06 UTC, yxlao commented
> Since our Open3DViewer uses legacy geometry for now if we want to support .npz in our current visualizer we may either support .npz in legacy io or check for extension locally in visualizer code to move this function there (I think, that will make the code more confusing).

I would drop it for now to keep things simple.

2021-08-05 07:43 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3851)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/io/PointCloudIO.h, line 190 at r1](https://reviewable.io/reviews/isl-org/open3d/3851#-Mg8MFde9lVyqrkzL6FV:-MgKFnSyDzvy0nZbYf7n:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/5f1767752537251408e3b2aa829d4cbae1780e56/cpp/open3d/io/PointCloudIO.h#L190)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Is this needed for the visualizer? If not, we can just drop it.
</blockquote></details>

Done.
___
*[cpp/open3d/t/io/PointCloudIO.cpp, line 183 at r1](https://reviewable.io/reviews/isl-org/open3d/3851#-Mg8Mbz0DI1UFoWhn0cm:-MgKFvrr2tsdTVy26FTK:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/5f1767752537251408e3b2aa829d4cbae1780e56/cpp/open3d/t/io/PointCloudIO.cpp#L183)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Does it work, if you do
```cpp
pointcloud = t::geometry::PointCloud(ReadNpz(filename));
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-06 07:07 UTC, yxlao approved these changes

2021-08-06 07:07 UTC, merged