Removed CPU() and CUDA() wrappers for device transfer in cpp.
isl-org/Open3D pull request #3854
Opened 2021-08-03 08:10 UTC by reyanshsolis

2021-08-03 12:08 UTC, yxlao requested changes

2021-08-03 12:08 UTC, yxlao commented on cpp/pybind/core/hashmap.cpp
> +                if (!core::cuda::IsAvailable()) {
Could these checks be made inside the `To()` function? Apply this to the rest of this PR for all pybinds.

2021-08-03 12:08 UTC, yxlao commented on cpp/pybind/core/hashmap.cpp
> +                return hashmap.To(core::Device(core::Device::DeviceType::CUDA,
`core::Device("CUDA", device_id)`, the first argument can be a string. 
Apply this change to all `DeviceType::CUDA` and `DeviceType::CPU` in this PR,

2021-08-03 12:08 UTC, yxlao commented on cpp/pybind/core/tensor.cpp
> +                return tensor.To(Device(Device::DeviceType::CPU, 0));
`To(Device("CPU:0"))`, same for the rest of this PR

2021-08-03 15:38 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3854)* status: 0 of 25 files reviewed, 3 unresolved discussions (waiting on @yxlao)

___
*[cpp/pybind/core/hashmap.cpp, line 120 at r1](https://reviewable.io/reviews/isl-org/open3d/3854#-MgA30RFuVxFbBLXWXKQ-r1-120:-MgBeS_q3H7Syqr7LFfD:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/b5821d3c71b366abc3057a7168aac7aaebb47944/cpp/pybind/core/hashmap.cpp#L120)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Could these checks be made inside the `To()` function? Apply this to the rest of this PR for all pybinds.
</blockquote></details>

Done.
___
*[cpp/pybind/core/hashmap.cpp, line 130 at r1](https://reviewable.io/reviews/isl-org/open3d/3854#-MgA30RFuVxFbBLXWXKQ-r1-130:-MgBeT192DCMsE1IgX3a:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/b5821d3c71b366abc3057a7168aac7aaebb47944/cpp/pybind/core/hashmap.cpp#L130)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

 `core::Device("CUDA", device_id)`, the first argument can be a string. 
Apply this change to all `DeviceType::CUDA` and `DeviceType::CPU` in this PR,
</blockquote></details>

Done.
___
*[cpp/pybind/core/tensor.cpp, line 478 at r1](https://reviewable.io/reviews/isl-org/open3d/3854#-MgA30RFuVxFbBLXWXKR-r1-478:-MgBeTy_3vgNVirN2Tr8:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/b5821d3c71b366abc3057a7168aac7aaebb47944/cpp/pybind/core/tensor.cpp#L478)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`To(Device("CPU:0"))`, same for the rest of this PR
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-03 16:17 UTC, reyanshsolis commented
@yxlao Do we want to support having CUDA Device object, even when Open3D is not built with CUDA.

eg. 
Even if Open3D is not built with CUDA, currently we allow this:
```python
device0 = o3c.Device("CUDA:-1")
print(device0) # CUDA:-1

device1 = o3c.Device("CUDA:1000")
print(device1) # CUDA:1000
```

Now, getting the `cuda::DeviceCount()` in `Device()` constructor will be difficult due to cyclic dependency, but we can block users from creating CUDA Device, when not built with CUDA enabled, or if the index is negative.

2021-08-04 06:49 UTC, yxlao commented
@reyanshsolis 

> Do we want to support having CUDA Device object, even when Open3D is not built with CUDA.

Yes. `o3c.Device("CUDA:1000")` should be allowed even when CUDA is not enabled. Even `o3c.Device("CUDA:1000")` should work. Similarly, if you only have one GPU, `o3c.Device("CUDA:1")` is allowed, but you can't allocate to this device.

> Now, getting the cuda::DeviceCount() in Device() constructor will be difficult due to cyclic dependency, 

This can be resolved by creating a `Device.cpp` and move all implementations from `Device.h` to `Device.cpp`. Remove all unnecessary includes from `Device.h` and add those includes in `Device.cpp`.

2021-08-04 07:05 UTC, reyanshsolis commented
Thanks for the clarification. 
If that is the case, then we might not need to make any changes to Device.h. Kindly let me know if any further changes are required.

2021-08-06 03:17 UTC, yxlao requested changes
> Reviewed 16 of 23 files at r1, 8 of 9 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/3854)* status: all files reviewed, 1 unresolved discussion (waiting on @reyanshsolis)

___
*[cpp/open3d/core/Tensor.cpp, line 557 at r3](https://reviewable.io/reviews/isl-org/open3d/3854#-MgOSJhwE3RARcGKbyEx:-MgOSJhwE3RARcGKbyEy:b8w50kz) ([raw file](https://github.com/isl-org/open3d/blob/a6d4a462bbf9e4e962c25cc149d69f1d003a4e1c/cpp/open3d/core/Tensor.cpp#L557)):*
> ```cpp
> // Checks if the device_id for CUDA is valid. For CPU Device ID == 0 is verified
> // in the Device constructor itself.
> static void AssertCUDADeviceID(const Device& device) {
> ```

We shouldn't need to check it here. It shall error gracefully in `kernel::Copy()`. 

If `kernel::Copy()` already errors gracefully, remove this check. Otherwise, update `kernel::Copy()`.


<!-- Sent from Reviewable.io -->

2021-08-06 03:29 UTC, yxlao approved these changes

2021-08-06 15:31 UTC, merged