added style check for license header
isl-org/Open3D pull request #4002
Opened 2021-08-31 15:16 UTC by ShubhamAgarwal12

Added license header style check for open3d files.

2021-09-14 07:06 UTC, yxlao requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4002)* status: all files reviewed, 9 unresolved discussions (waiting on @ShubhamAgarwal12)

___
*[util/check_style.py, line 182 at r2](https://reviewable.io/reviews/isl-org/open3d/4002#-MjY3jV23jb1VK1aEOLJ:-MjY3jV23jb1VK1aEOLK:b9py0gm) ([raw file](https://github.com/isl-org/open3d/blob/fdaf4d0bfda9bab1aa4f386e868983f6f41398ab/util/check_style.py#L182)):*
> ```Python
> 
>     @staticmethod
>     def _check_style(file_path, standard_header, clang_format_bin):
> ```

We shouldn't need to pass in `standard_header` as a class argument. We can simply refer to the static variable as `CppFormatter.standard_header`. Same for the python counterpart.
___
*[util/check_style.py, line 184 at r2](https://reviewable.io/reviews/isl-org/open3d/4002#-MjY3I0k3n2nrJ6ycYIG:-MjY3I0k3n2nrJ6ycYIH:bbq31wj) ([raw file](https://github.com/isl-org/open3d/blob/fdaf4d0bfda9bab1aa4f386e868983f6f41398ab/util/check_style.py#L184)):*
> ```Python
>     def _check_style(file_path, standard_header, clang_format_bin):
>         """
>         Returns (true, true) if (style, header) are valid.
> ```

nit: "is" valid, since this is one tuple. Update the python counterpart.
___
*[util/check_style.py, line 190 at r2](https://reviewable.io/reviews/isl-org/open3d/4002#-MjY1Z3P7soZgNhhnTtn:-MjY1Z3P7soZgNhhnTto:b49aakt) ([raw file](https://github.com/isl-org/open3d/blob/fdaf4d0bfda9bab1aa4f386e868983f6f41398ab/util/check_style.py#L190)):*
> ```Python
>         with open(file_path, 'r') as f:
>             content = f.read()
>             if content[:len(standard_header)] == standard_header:
> ```

Rewrite as:
```python
with open(file_path, 'r') as f:
    is_valid_header = f.read().startswith(standard_header)
```

Also, update the python counterpart of this.
___
*[util/check_style.py, line 243 at r2](https://reviewable.io/reviews/isl-org/open3d/4002#-MjY4Ed937u2MehMfnkN:-MjY4Ed937u2MehMfnkO:b-h8khws) ([raw file](https://github.com/isl-org/open3d/blob/fdaf4d0bfda9bab1aa4f386e868983f6f41398ab/util/check_style.py#L243)):*
> ```Python
> 
>         changed_files = []
>         files_wrong_header = []
> ```

nit: wrong_header_files` to be consistent to `changed_files`
___
*[util/check_style.py, line 298 at r2](https://reviewable.io/reviews/isl-org/open3d/4002#-MjY31D-4CN8rGSPGOOy:-MjY31D-4CN8rGSPGOOz:b-lij9bi) ([raw file](https://github.com/isl-org/open3d/blob/fdaf4d0bfda9bab1aa4f386e868983f6f41398ab/util/check_style.py#L298)):*
> ```Python
> 
>         is_valid_header = False
>         # Skip auto generated file "docs/conf.py"
> ```

Do this in the `__main__` function. Make a list of ignored files.
___
*[util/check_style.py, line 469 at r2](https://reviewable.io/reviews/isl-org/open3d/4002#-MjY26Er7GphyU7QwX42:-MjY26Er7GphyU7QwX43:b-ka2zt3) ([raw file](https://github.com/isl-org/open3d/blob/fdaf4d0bfda9bab1aa4f386e868983f6f41398ab/util/check_style.py#L469)):*
> ```Python
> 
>     # Check or apply style
>     cpp_formatter = CppFormatter(_glob_files(CPP_FORMAT_DIRS,
> ```

ignore `open3d/visualization/shader/Shader.h` here since it is generated
___
*[util/check_style.py, line 479 at r2](https://reviewable.io/reviews/isl-org/open3d/4002#-MjY65Yy6ZxBharcZyeH:-MjY65Yy6ZxBharcZyeI:bbhme5t) ([raw file](https://github.com/isl-org/open3d/blob/fdaf4d0bfda9bab1aa4f386e868983f6f41398ab/util/check_style.py#L479)):*
> ```Python
> 
>     changed_files = []
>     files_wrong_header = []
> ```

same, rename.
___
*[util/check_style.py, line 499 at r2](https://reviewable.io/reviews/isl-org/open3d/4002#-MjY5vrj6EDM79qKWnH3:-MjY5vrj6EDM79qKWnH4:bqep1zm) ([raw file](https://github.com/isl-org/open3d/blob/fdaf4d0bfda9bab1aa4f386e868983f6f41398ab/util/check_style.py#L499)):*
> ```Python
>                               verbose=args.verbose))
> 
>     if (len(changed_files) == 0 and len(files_wrong_header) == 0):
> ```

use python syntax, remove the outer `()`
___
*[util/check_style.py, line 508 at r2](https://reviewable.io/reviews/isl-org/open3d/4002#-MjY6Q7LELp4iJblSUl0:-MjY6Q7LELp4iJblSUl1:b-mgso3j) ([raw file](https://github.com/isl-org/open3d/blob/fdaf4d0bfda9bab1aa4f386e868983f6f41398ab/util/check_style.py#L508)):*
> ```Python
>             print("\n".join(changed_files))
>         if len(files_wrong_header) != 0:
>             print(
> ```

1. split the code into two lines (workaround the 80 char limit)
2. be consistent and use ":" at the end of the sentence, e.g. we can use `()` for the additional info
3. emphasize "manually"

Example:
```python
print("Please correct license header *manually* in the following files "
      "(see util/check_style.py for the standard header):")
```


<!-- Sent from Reviewable.io -->

2021-09-15 13:08 UTC, ShubhamAgarwal12 reviewed
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4002)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @yxlao)

___
*[util/check_style.py, line 182 at r2](https://reviewable.io/reviews/isl-org/open3d/4002#-MjY3jV23jb1VK1aEOLJ:-Mjd2Dxy57SVXqAZfurM:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/fdaf4d0bfda9bab1aa4f386e868983f6f41398ab/util/check_style.py#L182)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We shouldn't need to pass in `standard_header` as a class argument. We can simply refer to the static variable as `CppFormatter.standard_header`. Same for the python counterpart.
</blockquote></details>

Done.
___
*[util/check_style.py, line 190 at r2](https://reviewable.io/reviews/isl-org/open3d/4002#-MjY1Z3P7soZgNhhnTtn:-Mjd2HpX6XA3Nv7IHi2q:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/fdaf4d0bfda9bab1aa4f386e868983f6f41398ab/util/check_style.py#L190)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Rewrite as:
```python
with open(file_path, 'r') as f:
    is_valid_header = f.read().startswith(standard_header)
```

Also, update the python counterpart of this.
</blockquote></details>

Done.
___
*[util/check_style.py, line 243 at r2](https://reviewable.io/reviews/isl-org/open3d/4002#-MjY4Ed937u2MehMfnkN:-Mjd2PS21vNQmHfQkpPI:bajer72) ([raw file](https://github.com/isl-org/open3d/blob/fdaf4d0bfda9bab1aa4f386e868983f6f41398ab/util/check_style.py#L243)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

nit: wrong_header_files` to be consistent to `changed_files`
</blockquote></details>

wrong_header_files sounded a bit misleading so I didn't do it. I've changed it now.
___
*[util/check_style.py, line 298 at r2](https://reviewable.io/reviews/isl-org/open3d/4002#-MjY31D-4CN8rGSPGOOy:-MjdXkUG4oxSqqyvxtwj:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/fdaf4d0bfda9bab1aa4f386e868983f6f41398ab/util/check_style.py#L298)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Do this in the `__main__` function. Make a list of ignored files.
</blockquote></details>

Done.
___
*[util/check_style.py, line 469 at r2](https://reviewable.io/reviews/isl-org/open3d/4002#-MjY26Er7GphyU7QwX42:-MjdXmvZCxuKHMSPu9QV:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/fdaf4d0bfda9bab1aa4f386e868983f6f41398ab/util/check_style.py#L469)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

ignore `open3d/visualization/shader/Shader.h` here since it is generated
</blockquote></details>

Done.
___
*[util/check_style.py, line 479 at r2](https://reviewable.io/reviews/isl-org/open3d/4002#-MjY65Yy6ZxBharcZyeH:-Mjd3y8e3O3O3YOhzOZh:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/fdaf4d0bfda9bab1aa4f386e868983f6f41398ab/util/check_style.py#L479)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

same, rename.
</blockquote></details>

Done.
___
*[util/check_style.py, line 499 at r2](https://reviewable.io/reviews/isl-org/open3d/4002#-MjY5vrj6EDM79qKWnH3:-Mjd4IOxApdk5oV6bWSb:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/fdaf4d0bfda9bab1aa4f386e868983f6f41398ab/util/check_style.py#L499)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

use python syntax, remove the outer `()`
</blockquote></details>

Done.
___
*[util/check_style.py, line 508 at r2](https://reviewable.io/reviews/isl-org/open3d/4002#-MjY6Q7LELp4iJblSUl0:-Mjd5fnc8N2P7sxofEHR:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/fdaf4d0bfda9bab1aa4f386e868983f6f41398ab/util/check_style.py#L508)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

1. split the code into two lines (workaround the 80 char limit)
2. be consistent and use ":" at the end of the sentence, e.g. we can use `()` for the additional info
3. emphasize "manually"

Example:
```python
print("Please correct license header *manually* in the following files "
      "(see util/check_style.py for the standard header):")
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-16 05:24 UTC, yxlao reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4002)* status: all files reviewed, 4 unresolved discussions (waiting on @ShubhamAgarwal12 and @yxlao)

___
*[util/check_style.py, line 478 at r5](https://reviewable.io/reviews/isl-org/open3d/4002#-Mjh2v-0Acgdwm0d1qa8:-Mjh2v-0Acgdwm0d1qa9:b-b0mv18) ([raw file](https://github.com/isl-org/open3d/blob/352cac263c5cf13be836826f7081a2fd91c75305/util/check_style.py#L478)):*
> ```Python
> 
>     # Remove auto generated files
>     auto_generated_files = [
> ```

alternative approach: update these files to generate with license


<!-- Sent from Reviewable.io -->

2021-09-22 09:04 UTC, yxlao approved these changes

2021-09-22 09:05 UTC, merged