AddMM
isl-org/Open3D pull request #4184
Opened 2021-10-21 18:54 UTC by junha-l

`AddMM` similar with [pytorch's addmm](https://pytorch.org/docs/stable/generated/torch.addmm.html)

It computes the generalized matrix multiplication as follow: 
```
output  = alpha * mat1 @ mat2 + beta * input
```
where, `alpha`, `beta` are scalar values, `mat1`, `mat2`, and `input` are tensors.

`mat1` and `mat2` should be 2D matrices with shape (m, n), (n,k), 
and `input` should have a broadcastable shape with (m, k).

TODO:
- [x] transpose as function argument
- [x] broadcast add
- [x] pybind
- [x] C++ unit test
- [x] python unit test

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/open3d/4184)

2021-11-10 15:48 UTC, reyanshsolis commented on cpp/tests/core/Linalg.cpp
> +    C_data = C.ToFlatVector<float>();
modify test: use Init to initialize gt tensor, and use `EXPECT_TRUE T.AllClose(T_gt, EPSILON)`.
Same for other tests.

2021-11-10 15:48 UTC, reyanshsolis commented on cpp/pybind/core/linalg.cpp
> +            "Function to perform addmm of two 2D tensors with compatible "
mention the operation performed. ref. https://pytorch.org/docs/stable/generated/torch.addmm.html

2021-11-10 15:48 UTC, reyanshsolis commented on cpp/open3d/core/linalg/AddMM.h
> +/// Computes matrix multiplication C = AB.
may add `alpha` and `beta` also in the equation.

2021-11-10 15:48 UTC, reyanshsolis commented on cpp/open3d/core/linalg/AddMM.h
> +/// Computes matrix multiplication C = AB.
also add detail docstring, like https://pytorch.org/docs/stable/generated/torch.addmm.html

2021-11-10 15:48 UTC, reyanshsolis commented on cpp/open3d/core/linalg/AddMM.h
> +}  // namespace core
nit: add one line

2021-11-16 10:02 UTC, yxlao requested changes

2021-11-25 19:09 UTC, junha-l commented on cpp/open3d/core/linalg/AddMM.h
> +        const Tensor& A, const Tensor& B, Tensor& C, double alpha, double beta);
Currently, we do not have a use case for this.
We can address this in later PR

2021-12-10 05:46 UTC, yxlao approved these changes

2021-12-10 05:47 UTC, merged