Clarification to Build Documentation
isl-org/Open3D pull request #4284
Opened 2021-11-11 23:20 UTC by AlexZakIntel

2021-11-11 23:26 UTC, ssheorey requested changes

2021-11-11 23:26 UTC, ssheorey commented on docs/builddocs.rst
> +    # Navigate to the Open3D directory you have cloned
Can you add this before the code block (in the regular text)?

2021-12-21 19:24 UTC, ssheorey commented
![1_Overview](https://user-images.githubusercontent.com/41028320/146986379-57328766-d4b9-4858-81bb-761888660814.jpg)

2022-01-07 23:53 UTC, AlexZakIntel commented
![1_Overview](https://user-images.githubusercontent.com/93158890/148607427-9391c499-9fc5-4a38-89a4-fb088019ca0b.jpg)
![1_Cube](https://user-images.githubusercontent.com/93158890/148607529-ee0ae0de-05af-423d-932c-2a5a6c8d7bda.jpg)
![2_Sphere](https://user-images.githubusercontent.com/93158890/148607694-18e130f5-259d-483f-8d37-04e7d895dedb.jpg)
![4 PCD](https://user-images.githubusercontent.com/93158890/148607866-3de802e2-34ea-499e-a6ad-ee2b44ab9994.jpg)
![9_LineSet](https://user-images.githubusercontent.com/93158890/148608068-bd244820-a6c9-47e2-8ae8-1cabaeec907d.jpg)
![9a_line_width](https://user-images.githubusercontent.com/93158890/148608552-9c77846a-1cca-4a2e-8f05-5b062eea89be.jpg)
![9b_more_complex_line_set](https://user-images.githubusercontent.com/93158890/148608657-0780bc13-1b32-4875-89ba-d8f8320a7469.jpg)
![5 Multiple_obj](https://user-images.githubusercontent.com/93158890/148608769-647de97c-c530-4bf4-8db3-fc75ef646dc3.jpg)
![5a Sep_Multiple_obj](https://user-images.githubusercontent.com/93158890/148608860-361aa4e8-bf20-4435-bda0-fb27899f0f07.jpg)
![5b Multiple_obj_UI](https://user-images.githubusercontent.com/93158890/148608987-bd0a741d-f516-4a06-8f1b-0463d656c036.jpg)
![6d_Window_Title_dimensions](https://user-images.githubusercontent.com/93158890/148609189-e52bb398-e84e-4f83-9a54-53102ea0e80b.jpg)
![6 Geoms](https://user-images.githubusercontent.com/93158890/148609355-929ebd00-0adb-4634-9da7-0a82c4965cc9.jpg)
![6a Geoms_w_compute_normals](https://user-images.githubusercontent.com/93158890/148609453-fecf75bc-4cb9-4961-9197-26a250c9cacc.jpg)
![6b_Geoms_w_UI](https://user-images.githubusercontent.com/93158890/148609614-dcea315f-b937-445f-ac1e-f461f94eb55d.jpg)
![6c_Geoms_named_w_UI](https://user-images.githubusercontent.com/93158890/148609730-69d90faa-7083-42c5-9c5f-6f12d2e3efc4.jpg)
![7_show_skybox](https://user-images.githubusercontent.com/93158890/148610012-98d2fbef-1a81-43b5-a076-0335f5f4ee1e.jpg)
![7b_bg_color](https://user-images.githubusercontent.com/93158890/148610167-6a61f94b-8b1f-4f5a-ae36-038fdab25acd.jpg)
![8_point_size](https://user-images.githubusercontent.com/93158890/148610297-0243c452-074f-4d44-a169-cd01a4f9e62a.jpg)
![10_monkey](https://user-images.githubusercontent.com/93158890/148610827-4a8dc85f-5664-4f7a-b0da-1808387c9f71.jpg)
![10a_monkey_material](https://user-images.githubusercontent.com/93158890/148610882-14e6d348-1e8e-4bd9-b0ef-90fa884d9706.jpg)
![10b_mat_shader](https://user-images.githubusercontent.com/93158890/148611064-2fa5fe4c-b8cb-4588-ad46-df23cdf160be.jpg)
![11_monkey_model](https://user-images.githubusercontent.com/93158890/148611141-d424fc74-be7e-4833-913c-714fc3c4fbd2.jpg)
![12_monkey_ls](https://user-images.githubusercontent.com/93158890/148611269-78820f1d-b981-44a6-bb08-60c17d0bb45f.jpg)
![13_scale_ls_w_object](https://user-images.githubusercontent.com/93158890/148611540-7f4ea545-18bc-4562-b5c8-fb9e7cf60452.jpg)
![14a_cloning_gltf](https://user-images.githubusercontent.com/93158890/148611673-8af22794-75b0-49a6-babe-d0b50578c570.jpg)
![15_helmet](https://user-images.githubusercontent.com/93158890/148611761-40f95b2b-d257-4f2b-a8c0-60a73b159b96.jpg)
![15a_read_triangle_mesh](https://user-images.githubusercontent.com/93158890/148611814-09c6fe17-d209-439d-8ae9-c186387fd698.jpg)

2022-01-13 15:42 UTC, AlexZakIntel commented
![16_index_0](https://user-images.githubusercontent.com/93158890/149238095-5385d761-3bae-4172-ab45-1d47b6084d5c.jpg)
![16a_hose_low](https://user-images.githubusercontent.com/93158890/149238208-961a0a8d-ebb2-4621-aff1-8bfcdeced734.jpg)
![16b_RubberWood_low](https://user-images.githubusercontent.com/93158890/149238298-98a894cd-72a2-4c76-8e30-da89e26f2fa4.jpg)
![16c_GlassPlastic_low](https://user-images.githubusercontent.com/93158890/149238367-e32d7d12-5472-4f83-90ff-e365c77ef30a.jpg)
![16d_MetalParts_low](https://user-images.githubusercontent.com/93158890/149238437-b225282b-afae-40a2-a485-7f13e0f3122d.jpg)
![16e_LeatherParts_low](https://user-images.githubusercontent.com/93158890/149238516-3f6a95f4-6c48-43b6-82e2-8363d0c30197.jpg)
![16f_Lenses_low](https://user-images.githubusercontent.com/93158890/149238634-7919b93d-1307-4ce4-9eb0-646237eceb6e.jpg)
![17a_Hose_low](https://user-images.githubusercontent.com/93158890/149238906-065fad20-ed3f-4585-b90b-7d30b5c06912.jpg)
![17b_RubberWood_low](https://user-images.githubusercontent.com/93158890/149239024-e361bb4a-5fe5-44e7-b41d-8b6d777a1b9b.jpg)
![17c_GlassPlastic_low](https://user-images.githubusercontent.com/93158890/149239132-cea7ad0d-3f42-4a69-a45b-9161c6e43deb.jpg)
![17d_MetalParts_low](https://user-images.githubusercontent.com/93158890/149239248-b884fa06-c121-4c06-a8fd-ef06bc992638.jpg)
![17e_LeatherParts_low](https://user-images.githubusercontent.com/93158890/149239346-13e07cd5-1d47-49b6-b43c-7840b01348e9.jpg)
![17f_Lenses_low](https://user-images.githubusercontent.com/93158890/149239403-e6fa3954-8cce-47be-b5b5-b388e7250fe4.jpg)

2022-01-18 19:44 UTC, AlexZakIntel commented
![13_scale_ls_w_object_a](https://user-images.githubusercontent.com/93158890/150007017-08b1c946-0280-474e-93ee-1840913bd61f.jpg)

2022-02-01 23:20 UTC, AlexZakIntel commented
![13_scale_ls_w_object_a](https://user-images.githubusercontent.com/93158890/150007965-4959165f-688d-43c0-a839-c1b8efea7073.jpg)
![14a_cloning_gltf_a](https://user-images.githubusercontent.com/93158890/150047410-de591582-67c5-42bd-b644-764c36b8c4b8.jpg)


![2b1  Lit Sphere](https://user-images.githubusercontent.com/93158890/150879488-bc887a9b-cb7a-4476-ab8e-3f72c185c604.jpg)
![2b2  Colored Lit Sphere](https://user-images.githubusercontent.com/93158890/150881545-56de6d95-50d0-4965-b2a0-b6bd27340df7.jpg)
![2b3  Drawing a Sphere With Materials](https://user-images.githubusercontent.com/93158890/150883605-a5e65a3f-0a25-4ff4-b039-4aa6e53a1440.jpg)

2022-03-04 00:55 UTC, AlexZakIntel commented
![compute_triangle_normals](https://user-images.githubusercontent.com/93158890/156677293-716c9834-3a58-4428-aa75-eff755b5a8bb.jpg)

2022-03-08 22:22 UTC, AlexZakIntel commented
![1a_cube_compute_vertex_normals](https://user-images.githubusercontent.com/93158890/157335716-a31a2f65-cb39-4038-9798-887ddd21201a.jpg)

2022-03-09 18:17 UTC, AlexZakIntel commented
![2a_Sphere_compute_vertex_normals](https://user-images.githubusercontent.com/93158890/157339234-1a92a944-ac38-4256-8297-0ad78fd24b9c.jpg)

2022-03-10 18:37 UTC, AlexZakIntel commented
![1a_cube_compute_triangle_normals](https://user-images.githubusercontent.com/93158890/157720147-cde9a54b-cba5-480e-ba0e-7784b5bd5677.jpg)
![2a_Sphere_compute_triangle_normals_faceted_sphere](https://user-images.githubusercontent.com/93158890/157728100-0a495e56-c613-40c4-a292-6e45213d61f6.jpg)

2022-03-10 23:33 UTC, AlexZakIntel commented
![3_metallic_sphere](https://user-images.githubusercontent.com/93158890/157758092-9efb1ca0-b96a-4e1d-abd7-95243b279d2e.jpg)

![3a_glossy_non_metallic_sphere](https://user-images.githubusercontent.com/93158890/157770798-2c42e7dc-e063-4f26-90b4-16a45e263f36.jpg)

2022-03-15 00:37 UTC, AlexZakIntel commented
![3b_textured_sphere](https://user-images.githubusercontent.com/93158890/157775220-443aad2d-9123-42d0-b584-31e9fb8f38c3.jpg)

![3c_aabb_lineset](https://user-images.githubusercontent.com/93158890/157901535-fbe78fc0-9b85-476e-a0a1-01e0e5d80738.jpg)

![3d_TriangleMesh_LineSet_sphere](https://user-images.githubusercontent.com/93158890/157949589-8b87fa81-a5cf-4791-a4f7-2d5dc91e546e.jpg)

![3d_TriangleMesh_LineSet_line_width_sphere](https://user-images.githubusercontent.com/93158890/157990732-28613b20-da4d-4225-bcc7-cd0f924a5bfd.jpg)

![3d_TriangleMesh_LineSet_line_width1_sphere](https://user-images.githubusercontent.com/93158890/157993716-83aab1cd-c558-4e50-b2fd-7bd82d5092e5.jpg)

![3e_1_ui_win_title_dimensions](https://user-images.githubusercontent.com/93158890/158281728-994ff828-53b0-485a-9feb-9b121d7354f7.jpg)

![3e_2_ui_named_objects](https://user-images.githubusercontent.com/93158890/158282041-a227b0f5-803e-4618-a9b1-d732c5de1a81.jpg)

![3e_3_named_geometry_objects](https://user-images.githubusercontent.com/93158890/158282171-b69a46c1-c5c6-44fc-a9fc-765e5ecc7473.jpg)

2022-03-15 23:06 UTC, AlexZakIntel commented
![3f_1_show_skybox_and_bg_color](https://user-images.githubusercontent.com/93158890/158435806-cf5180a4-3593-42df-a259-a6648a0e7b7e.jpg)

![3f_2_bg_color_green](https://user-images.githubusercontent.com/93158890/158464565-f36b1906-9337-4a8d-a707-d8a8ea962538.jpg)

2022-03-16 21:33 UTC, AlexZakIntel commented
![3f_1_show_skybox_and_bg_color](https://user-images.githubusercontent.com/93158890/158435806-cf5180a4-3593-42df-a259-a6648a0e7b7e.jpg)

![3f_2_bg_color_green](https://user-images.githubusercontent.com/93158890/158464565-f36b1906-9337-4a8d-a707-d8a8ea962538.jpg)

2022-03-16 23:05 UTC, AlexZakIntel commented
![3c_aabb_lineset_line_width_50](https://user-images.githubusercontent.com/93158890/158695002-f5976bfa-1e81-46dc-bf3b-b926d0c5e0af.jpg)

![3c_aabb_lineset_line_width_1](https://user-images.githubusercontent.com/93158890/158695717-042343a4-bbc3-45b8-ab6b-1118ad027cd7.jpg)

2022-03-17 00:41 UTC, AlexZakIntel commented
![3c_aabb_lineset_line_width_50](https://user-images.githubusercontent.com/93158890/158695002-f5976bfa-1e81-46dc-bf3b-b926d0c5e0af.jpg)

![3c_aabb_lineset_line_width_1](https://user-images.githubusercontent.com/93158890/158695717-042343a4-bbc3-45b8-ab6b-1118ad027cd7.jpg)

2022-03-17 00:41 UTC, closed without merging

2022-03-17 15:08 UTC, AlexZakIntel commented
![3c_aabb_lineset_line_width_50](https://user-images.githubusercontent.com/93158890/158695002-f5976bfa-1e81-46dc-bf3b-b926d0c5e0af.jpg)

![3c_aabb_lineset_line_width_1](https://user-images.githubusercontent.com/93158890/158695717-042343a4-bbc3-45b8-ab6b-1118ad027cd7.jpg)

2022-03-18 19:49 UTC, AlexZakIntel commented
![1_Overview_added_math](https://user-images.githubusercontent.com/93158890/159073961-821e4768-3678-4385-bc37-20c5b212c030.jpg)

2022-03-18 22:51 UTC, AlexZakIntel commented
![3e_2_ui_named_objects](https://user-images.githubusercontent.com/93158890/159092908-a2462f6d-34fc-4703-9845-9b311a7f1630.jpg)

![3e_3_named_geometry_objects](https://user-images.githubusercontent.com/93158890/159093029-0c589006-e816-44a4-8f35-e224b106dddb.jpg)

![3f_1_show_skybox_and_bg_color](https://user-images.githubusercontent.com/93158890/159093215-31dcacf7-306f-4231-9155-0df474ce4828.jpg)

![3f_2_bg_color_green](https://user-images.githubusercontent.com/93158890/159093304-d92d87e9-7429-4bb4-92d8-c93eba3f2704.jpg)

2022-03-25 15:45 UTC, AlexZakIntel commented
![18_read_triangle_mesh](https://user-images.githubusercontent.com/93158890/160008560-4834c962-efa7-4d69-b99d-9ff321a03c02.jpg)

2022-03-25 22:51 UTC, AlexZakIntel commented
![dataset_splits](https://user-images.githubusercontent.com/93158890/160211785-6038581c-7987-467d-8fea-66aae63bf6fe.jpg)

2022-03-28 23:30 UTC, AlexZakIntel commented
![dataset_coordinates](https://user-images.githubusercontent.com/93158890/160503607-76e77f7a-56be-4fba-91c5-7e35019f68e8.jpg)

2022-03-29 14:23 UTC, AlexZakIntel commented
![dataset_splits](https://user-images.githubusercontent.com/93158890/160633509-e190d8ea-7d3c-4eea-a00f-29ba215b7e69.jpg)

2022-03-30 18:20 UTC, AlexZakIntel commented
![3f_2_bg_color_green](https://user-images.githubusercontent.com/93158890/160878317-a57755a0-8b8f-44db-b718-443aa435035a.jpg)
![2b2  Colored Lit Sphere](https://user-images.githubusercontent.com/93158890/160883817-5a22f449-62e2-45e0-8033-bfec72e09210.jpg)

2022-04-09 00:35 UTC, AlexZakIntel commented
![dataset_structure](https://user-images.githubusercontent.com/93158890/162548755-28c541d3-3557-4903-a9a1-cc685d16dfc2.jpg)

2022-04-12 20:17 UTC, AlexZakIntel commented
![dataset_coordinates](https://user-images.githubusercontent.com/93158890/162549410-6369cbd0-b835-4216-ba54-945e3f591395.jpg)

2022-04-22 17:55 UTC, AlexZakIntel commented
![1 cube_compute_vertex_normals](https://user-images.githubusercontent.com/93158890/164767767-4e980277-3125-4cdc-8b44-454459c2ea3c.jpg)

2022-04-22 20:15 UTC, AlexZakIntel commented
![1 cube_compute_vertex_normals](https://user-images.githubusercontent.com/93158890/164767767-4e980277-3125-4cdc-8b44-454459c2ea3c.jpg)

2022-04-22 20:40 UTC, AlexZakIntel commented
![3 UI_title_win_dimensions](https://user-images.githubusercontent.com/93158890/164787559-2e335866-7f6b-43c8-88bf-7646624eb618.png)

2022-04-22 20:58 UTC, AlexZakIntel commented
![3 UI_title_win_dimensions](https://user-images.githubusercontent.com/93158890/164792527-121548f0-dacc-4197-a0cf-dec287d2d3bb.jpg)

2022-04-22 23:11 UTC, AlexZakIntel commented
![4 Named_geometry_objects](https://user-images.githubusercontent.com/93158890/164792623-795b80c3-332b-46be-9886-2ca9bf2a34f8.jpg)

![5 Raw_mode](https://user-images.githubusercontent.com/93158890/164815973-2f291675-d43a-47a7-a8fe-38af225b9948.jpg)