made set/get geomety transform available in python
isl-org/Open3D pull request #4366
Opened 2021-12-02 12:33 UTC by mag-sruehl

this PR exposes SetGeometryTransform, GetGeometryTransform and GeometryIsVisible to the python API which allows us to show animations in the open3d.visualization.gui.SceneWidget

2021-12-08 17:42 UTC, ssheorey commented
@mag-sruehl To fix the CI errors, please:
- Merge master. This should fix the errors in documentation and OpenBlas CIs that were caused due to some CI infrastructure issues.
- Run `make apply-style`. This will apply Open3D formatting, based on clang-format.

2021-12-09 13:20 UTC, mag-sruehl commented
Hello @ssheorey and thank you for your help. I have updated the PR as you have suggested, but I get an error message from make apply-style:

...
Please correct license header *manually* in the following files (see util/check_style.py for the standard header):
/home/ruehl/src/Open3D/cpp/open3d/core/CMakeFiles/core.dir/BinaryEWCPU_ispc.h
...

The files touched by this PR seem to be fine so I would  like to avoid fixing the others.

2021-12-10 15:59 UTC, ssheorey commented
CI looks good now. Thanks @mag-sruehl . This is ready for review.

2021-12-13 16:50 UTC, errissa requested changes
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4366)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @errissa and @mag-sruehl)

___
*[cpp/pybind/visualization/rendering/rendering.cpp, line 623 at r2](https://reviewable.io/reviews/isl-org/open3d/4366#-MqogalcEqlxfqaxX1Zi:-MqogalcEqlxfqaxX1Zj:b-jewhtl) ([raw file](https://github.com/isl-org/open3d/blob/638f2431f0f3c85502d6512f9e541521a8ff7495/cpp/pybind/visualization/rendering/rendering.cpp#L623)):*
> ```cpp
>                  "Removes the geometry with the given name")
>             .def("geometry_is_visible", &Open3DScene::GeometryIsVisible,
>                  "is the geometry visible")
> ```

Would you please improve the three doc strings for the new functions? See `has_geometry` above for an example. I know we aren't consistent with our doc strings and many are not very good but we are trying to improve.


<!-- Sent from Reviewable.io -->

2021-12-14 14:09 UTC, errissa approved these changes
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4366)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mag-sruehl)



<!-- Sent from Reviewable.io -->

2021-12-14 14:28 UTC, mag-sruehl commented
> > Reviewed 1 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4366)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mag-sruehl)

Sorry for being a github noob: what am I supposed to do what _Reviewable_ is waiting for?

2021-12-14 14:34 UTC, errissa commented
> > > Reviewed 1 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> > > _[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4366)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mag-sruehl)
> 
> Sorry for being a github noob: what am I supposed to do what _Reviewable_ is waiting for?

Nothing you need to do. I already approved the PR. Once it passes CI I will merge it. Thank you for your contribution!

2021-12-14 20:55 UTC, merged