fix nan in normal image
isl-org/Open3D pull request #4438
Opened 2021-12-16 09:40 UTC by Fuhrmann-sep

2021-12-23 02:11 UTC, ssheorey requested changes
Hi @Fuhrmann-sep thanks for submitting this PR. To pass the CI checks, can you:
- Run `make apply-style` to pass the style checks.
- The normal CI tests are failing since this will change the values of the estimated normals. An alternate way to avoid NaN is:
`normal_norm = std::max(normal_norm, EPSILON);` instead of adding 1e-5 (a magic number). Define `constexpr float EPSILON = 1e-5f`;  so that readers understand the code. This will ensure that the normals are unchanged when they are not NaN.

2021-12-23 09:52 UTC, Fuhrmann-sep commented
Hello, @ssheorey thank you for the reminder. Modifications are done and another commit is added.

2021-12-23 16:46 UTC, ssheorey commented
> Hello, @ssheorey thank you for the reminder. Modifications are done and another commit is added.

Thanks @Fuhrmann-sep You need `std::max`.

2021-12-27 17:36 UTC, ssheorey approved these changes

2022-01-12 04:53 UTC, merged