Enable python 3.10
isl-org/Open3D pull request #4463
Opened 2021-12-18 15:21 UTC by yxlao

For now, we don't release 3.10 wheel since PyTorch/TensorFlow does not support 3.10. 

However, we can still enable the 3.10 build-from-source option for users. 

Fixes #4461

2021-12-20 15:29 UTC, ssheorey reviewed
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4463)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ssheorey and @yxlao)

___
*[CMakeLists.txt, line 249 at r1](https://reviewable.io/reviews/isl-org/open3d/4463#-MrNSK8Q3NbhO37AMhq_:-MrNSK8Q3NbhO37AMhqa:b-cjtj0f) ([raw file](https://github.com/isl-org/open3d/blob/c2a344e85c932630d34e341095d6ed383d593723/CMakeLists.txt#L249)):*
> ```CMake
>     set(Python3_FIND_REGISTRY NEVER)
> endif()
> find_package(Python3 3.6...3.10
> ```

`find_package(Python3 3.6`
I think Python API is stable enough that we can just say >=3.6 instead of >=3.6 and <=3.10. Everything should very likely work for 3.11 as well when it comes out.


<!-- Sent from Reviewable.io -->

2021-12-20 22:24 UTC, odysseusPolytropos requested changes
If the intent was to accept all minor versions Python 3.10, this change is not correct. It will reject e.g. 3.10.1. To accept all Python 3.10 (but excluding 3.11 and following) line 249 should be:
 find_package(Python3 3.6...<3.11)

2021-12-21 07:14 UTC, yxlao commented
Thanks @ssheorey @odysseusPolytropos . Updated to support Python 3.6+.

2021-12-21 12:03 UTC, odysseusPolytropos approved these changes
:+1:

2021-12-21 12:04 UTC, odysseusPolytropos approved these changes

2021-12-21 12:10 UTC, merged

2022-07-01 13:41 UTC, MrBenGriffin commented
both TensorFlow and PyTorch are now supported in 3.10