fix call to AdvancedMatching in FGR
isl-org/Open3D pull request #4479
Opened 2021-12-22 04:40 UTC by plusk01

the `FastGlobalRegisrationBasedOnCorrespondence` function from https://github.com/isl-org/Open3D/pull/4188 has a bug in it (does not affect the original `FastGlobalRegistrationBasedOnFeatureMatching`)

the check on if `source` or `target` has more points (which was copied from `FastGlobalRegistrationBasedOnFeatureMatching`)  is useful so that the smaller set of points is used as the query in `InitialMatching`. This check was copied into the new `FastGlobalRegisrationBasedOnCorrespondence` function, but does not use `InitialMatching` -- i.e., the initial matches come from  the user. In this case, it does not make sense to swap the source/target based on number of points and in fact by swapping them but not swapping the "columns" of `corresvec` results in incorrect initial matches.

2021-12-23 15:41 UTC, theNded requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4479)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @plusk01 and @yxlao)

___
*[cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp, line 323 at r1](https://reviewable.io/reviews/isl-org/open3d/4479#-Mrbx2sn9q1hqmgph25M:-Mrbx2sn9q1hqmgph25N:b-kvg8a8) ([raw file](https://github.com/isl-org/open3d/blob/9e384236edfb2914854fe60f93f866c8c4e5f085/cpp/open3d/pipelines/registration/FastGlobalRegistration.cpp#L323)):*
> ```cpp
>             corresvec = AdvancedMatching(source, target, corresvec, option);
>         } else {
>             corresvec = AdvancedMatching(target, source, corresvec, option);
> ```

How about changing the order of these two lines?
```
  for (auto& p : corresvec) std::swap(p.first, p.second);
  corresvec = AdvancedMatching(target, source, corresvec, option);
```


<!-- Sent from Reviewable.io -->

2022-01-06 02:33 UTC, plusk01 commented
thanks @theNded - that is essentially what i am doing by removing the `if` statement altogether. In this case (when the correspondences are specified by the user and so the `InitialMatching` function is not called), there is no point checking if the `source` or `target` has more points.

2022-01-06 20:27 UTC, theNded commented
#4188 has introduced bugs in #4481 and #4522, and this PR does not address them. I will have to revisit #4188 and consider whether to revert it before moving forward with this PR.

2022-02-03 13:47 UTC, theNded commented
Sorry for coming back late, I forgot about this PR.
Actually, after the changes from this PR, the problem from #4481 reappears. Would you like to investigate?

2022-03-08 15:32 UTC, plusk01 commented
now it's my turn to apologize for coming back late @theNded :)
i just rebased this PR on master and tested on the example of #4481 - I did not see the issue again. I am wondering if you had rebased to include the fixes from #4547 ?

2022-06-10 03:45 UTC, nkapgate commented
I am seeing some crashes due to memory leak on Linux and Intel macs, is this issue fixable?

2022-06-10 09:50 UTC, plusk01 commented
Hi @nkapgate, do you have an small example that this PR is failing on?

2023-01-24 17:46 UTC, ssheorey commented
Check for crash, else merge.

2023-01-24 17:49 UTC, theNded commented
> Check for crash, else merge.

We can merge now. FGR has a lot of issues and is very slow now, no longer a "fast" method. Needs a complete rewrite. I will collect and fix existing issues in a separate PR.

2023-01-24 17:50 UTC, theNded approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4479#-:-NMZtlsv2l2z6oGn8VFj:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @plusk01 and @ssheorey)



<!-- Sent from Reviewable.io -->

2023-01-24 18:49 UTC, ssheorey approved these changes
Tested no crash with example code from #4481. LGTM.

2023-01-24 18:49 UTC, merged