Adding Dataset Functionalities.
isl-org/Open3D pull request #4583
Opened 2022-01-12 06:09 UTC by reyanshsolis

2022-01-13 05:57 UTC, yxlao requested changes
> Reviewed 4 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4583)* status: all files reviewed, 12 unresolved discussions (waiting on @reyanshsolis)

___
*[cpp/open3d/data/Dataset.h, line 30 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGw98UBmj1_suBmBld:-MtGw98UBmj1_suBmBle:bfsi722) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L30)):*
> ```objc
> 
> #include <string>
> #include <unordered_map>
> ```

remove unordered_map
___
*[cpp/open3d/data/Dataset.h, line 40 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGwWuFDG5zK8ieX1Qj:-MtGwWuFDG5zK8ieX1Qk:b2dxz40) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L40)):*
> ```objc
> /// A dataset class locates the data root directory in the following order:
> ///
> /// (a) User-specified by `data_root` when instantiating a dataset object.
> ```

Remove (a).

Future: shall we have a global function to set data root globally, instead of setting data root for each dataset sub-class? Similar to `utility::Logging::SetLoggingLevel()` sets a global flag.
___
*[cpp/open3d/data/Dataset.h, line 73 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGwnLX66qhhLD6NdLa:-MtGwnLX66qhhLD6NdLb:boi3vqn) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L73)):*
> ```objc
>     Dataset(const std::string& prefix, const std::string& data_root = "");
> 
>     ~Dataset() {}
> ```

It's recommended to use a virtual destructor if a class is inherited. https://stackoverflow.com/a/8752126/1255535
___
*[cpp/open3d/data/Dataset.h, line 75 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGxKlxAbr52kc_S9_5:-MtGxKlxAbr52kc_S9_6:b7g4adv) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L75)):*
> ```objc
>     ~Dataset() {}
> 
>     void DeleteDownloadFiles() const;
> ```

Remove the `Delete*`.
___
*[cpp/open3d/data/Dataset.h, line 88 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGyX_X4HV84HhSFN-J:-MtGyX_X4HV84HhSFN-K:b-lgxl2j) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L88)):*
> ```objc
> public:
>     /// Dataset prefix.
>     std::string prefix_;
> ```

If the user says `prefix_ = "xxx";`, now `extract_prefix_` is invalid.
___
*[cpp/open3d/data/Dataset.h, line 97 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGyrG-DBljnvxiNbt8:-MtGyrG08igNdjNyuGTu:b-vstkxl) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L97)):*
> ```objc
> protected:
>     /// extract_prefix_ = "/extract/" + prefix_
>     std::string extract_prefix_;
> ```

If a member can be derived from another member, we shall remove redundancy. 

```
std::string GetExtractDir() const {

}
```
___
*[cpp/open3d/data/Dataset.h, line 106 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtH-6q02GckS2rdCEFl:-MtH-6q02GckS2rdCEFm:b-xindyj) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L106)):*
> ```objc
> };
> 
> class TemplateDataset : public Dataset {
> ```

`SimpleDataset`
___
*[cpp/open3d/data/Dataset.h, line 109 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGzn7e2onmE_MHyfkO:-MtGzn7e2onmE_MHyfkP:bk0ad5i) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L109)):*
> ```objc
> public:
>     TemplateDataset(const std::string& prefix,
>                     const std::vector<std::string>& url_mirrors,
> ```

Nit: `urls`
___
*[cpp/open3d/data/Dataset.h, line 114 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGxw8a5SmPFsIEV7jq:-MtGxw8a5SmPFsIEV7jr:b-gzzyhc) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L114)):*
> ```objc
>                     const std::string& data_root = "");
> 
>     ~TemplateDataset() {}
> ```

`virtual`
___
*[cpp/open3d/data/Dataset.h, line 136 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGzymq9S_9yxtrkSDT:-MtGzymq9S_9yxtrkSDU:b2estyn) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L136)):*
> ```objc
> 
>         // clang-format off
>         Dataset::help_ = 
> ```

Avoid red dots
Use better string literals. 
___
*[cpp/open3d/data/Download.h, line 75 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtH-GKp21Zcf-L1KjfA:-MtH-GKp21Zcf-L1KjfB:b31we1b) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Download.h#L75)):*
> ```objc
> /// \returns Path to downloaded file.
> /// \throw std::runtime_error If the download fails.
> std::string DownloadFromMirrorURLs(const std::vector<std::string>& url_mirrors,
> ```

`DownloadFromURLs`
___
*[cpp/tests/utility/FileSystem.cpp, line 347 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGuVQZASRoQDQq_oos:-MtGuVQZASRoQDQq_oot:bungg2q) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/tests/utility/FileSystem.cpp#L347)):*
> ```cpp
> // ----------------------------------------------------------------------------
> // Note: DeleteDirectory can delete one dir at a time.
> // Equivalent to 'rm -rf ...'.
> ```

nit: Use backtick instaed of single quote 


<!-- Sent from Reviewable.io -->

2022-01-13 07:46 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4583)* status: 1 of 7 files reviewed, 10 unresolved discussions (waiting on @yxlao)

___
*[cpp/open3d/data/Dataset.h, line 30 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGw98UBmj1_suBmBld:-MtHOJVT6mzhfZ7YcJ9n:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L30)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

remove unordered_map
</blockquote></details>

Done.
___
*[cpp/open3d/data/Dataset.h, line 40 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGwWuFDG5zK8ieX1Qj:-MtHOJuNB8u6P60HKLLH:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L40)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Remove (a).

Future: shall we have a global function to set data root globally, instead of setting data root for each dataset sub-class? Similar to `utility::Logging::SetLoggingLevel()` sets a global flag.
</blockquote></details>

Done.
___
*[cpp/open3d/data/Dataset.h, line 73 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGwnLX66qhhLD6NdLa:-MtHOKZZ0XtkuO71Au9b:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L73)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

It's recommended to use a virtual destructor if a class is inherited. https://stackoverflow.com/a/8752126/1255535
</blockquote></details>

Done.
___
*[cpp/open3d/data/Dataset.h, line 75 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGxKlxAbr52kc_S9_5:-MtHOKu759C3Ummizscu:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L75)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Remove the `Delete*`.
</blockquote></details>

Done.
___
*[cpp/open3d/data/Dataset.h, line 88 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGyX_X4HV84HhSFN-J:-MtHOXVg5HbTfEOVSV20:bt2vr1b) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L88)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

If the user says `prefix_ = "xxx";`, now `extract_prefix_` is invalid.
</blockquote></details>

Fixed.
___
*[cpp/open3d/data/Dataset.h, line 97 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGyrG-DBljnvxiNbt8:-MtHOWIR1RlUldyUSj00:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L97)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

If a member can be derived from another member, we shall remove redundancy. 

```
std::string GetExtractDir() const {

}
```
</blockquote></details>

Done.
___
*[cpp/open3d/data/Dataset.h, line 106 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtH-6q02GckS2rdCEFl:-MtHOUR6-MXsjuvmRzUb:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L106)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`SimpleDataset`
</blockquote></details>

Done.
___
*[cpp/open3d/data/Dataset.h, line 109 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGzn7e2onmE_MHyfkO:-MtHOTL581TLLX9tV_tb:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L109)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Nit: `urls`
</blockquote></details>

Done.
___
*[cpp/open3d/data/Dataset.h, line 114 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGxw8a5SmPFsIEV7jq:-MtHOQMg9jhn-6D1ON5J:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L114)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`virtual`
</blockquote></details>

Done.
___
*[cpp/open3d/data/Dataset.h, line 136 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGzymq9S_9yxtrkSDT:-MtHOPsHAuprugVe7Xuu:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Dataset.h#L136)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Avoid red dots
Use better string literals. 
</blockquote></details>

Done.
___
*[cpp/open3d/data/Download.h, line 75 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtH-GKp21Zcf-L1KjfA:-MtHObSI-rWABO5hvvW9:b-g5dyy2) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/open3d/data/Download.h#L75)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

`DownloadFromURLs`
</blockquote></details>

`DownloadFromURL` overload might allow for simpler use. Do we still want to add the `s` ?
___
*[cpp/tests/utility/FileSystem.cpp, line 347 at r2](https://reviewable.io/reviews/isl-org/open3d/4583#-MtGuVQZASRoQDQq_oos:-MtHOoUZBUOcNKIlVhke:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/824cf2d7dadb79fdcff58903938b3fd1d1e8b8e3/cpp/tests/utility/FileSystem.cpp#L347)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

nit: Use backtick instaed of single quote 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-18 07:47 UTC, reyanshsolis commented on cpp/tests/geometry/PointCloud.cpp
> +    io::ReadPointCloud(pcd_fragments.path_to_fragments_[0], pcd);
`fragment.ply` / `fragment.pcd` / `cloud_bin_0.pcd`, are similar data (slightly different in terms of exact number of points), therefore used `cloud_bin_0.pcd` from `SamplePCDFragment` dataset consistently, and modified the unit test expected results, as required.

2022-01-20 06:01 UTC, yxlao requested changes
> Reviewed 2 of 6 files at r3, 8 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4583)* status: 11 of 15 files reviewed, 4 unresolved discussions (waiting on @reyanshsolis and @yxlao)

___
*[cpp/tests/geometry/PointCloud.cpp, line 1192 at r4](https://reviewable.io/reviews/isl-org/open3d/4583#-MtJHOIBhBkotxYAP9Tm-r4-1192:-Mtq-s8BAAyVDtZm0fiV:b-dddhei) ([raw file](https://github.com/isl-org/open3d/blob/9c22aaf4896743d5088c293ac9a89dfffa80d915/cpp/tests/geometry/PointCloud.cpp#L1192)):*
<details><summary><i>Previously, reyanshsolis (Rishabh Singh) wrote…</i></summary><blockquote>

`fragment.ply` / `fragment.pcd` / `cloud_bin_0.pcd`, are similar data (slightly different in terms of exact number of points), therefore used `cloud_bin_0.pcd` from `SamplePCDFragment` dataset consistently, and modified the unit test expected results, as required.
</blockquote></details>

- Rename `SamplePCDFragments` -> `SampleICPPointClouds`: for the dataset with 3 point clouds
- `SamplePCDPointCloud` for `fragment.pcd`
- `SamplePLYPointCloud` for `fragment.ply`
___
*[cpp/tests/geometry/PointCloud.cpp, line 1209 at r5](https://reviewable.io/reviews/isl-org/open3d/4583#-Mtq0XH88yxgai0_Rc9X:-Mtq0XH88yxgai0_Rc9Y:br9cid) ([raw file](https://github.com/isl-org/open3d/blob/98af9a1a1afbaf5050117f3ce17c51f2aaf3dc53/cpp/tests/geometry/PointCloud.cpp#L1209)):*
> ```cpp
>     data::dataset::SamplePCDFragments pcd_fragments;
>     geometry::PointCloud pcd;
>     io::ReadPointCloud(pcd_fragments.path_to_fragments_[0], pcd);
> ```

```cpp
string MyDataset::GetPath()  const;   // If the dataset has one path
vector<string> MyDataset::GetPaths() const;  // If the dataset has more than one paths
string MyDataset::GetPaths(size_t index)  const;  // If the dataset has more than one paths

MyDataset::GetRGBPaths()  const;
MyDataset::GetDepthPaths()  const;
MyDataset::GetCameraTrajectoryPath()  const;
```

```python
md = MyDataset()
md.path  # Pybind read-only property bind to `GetPath()` function.
md.paths  # Pybind read-only property bind to `GetPaths()` function.

md.rgb_paths[5]
md.depth_paths
md.camera_trajectory_path
```

```cpp
tensor.def_property_readonly("dtype", &Tensor::GetDtype);
tensor.def_property_readonly("device", &Tensor::GetDevice);
tensor.def_property_readonly("blob", &Tensor::GetBlob);
````

Benefits for using functions:
- We don't need to create new states in class.
- Avoid public members (public members are typically bad design in C++).
- Implement logic in getter function to derive path from root.


<!-- Sent from Reviewable.io -->

2022-01-20 16:10 UTC, yxlao commented
> `def_property_*` cannot accept an argument, therefore it can not be used for `GetExtractDir(bool relative_to_data_root = false), GetDownloadDir(bool relative_to_data_root = false), GetPath(size index)`. So `def` is used.

Sounds good. But do we need actually need to expose `GetExtractDir` and `GetDownloadDir` in Python?

> The Path and Paths design might lead to some confusion

What is the confusion? 

In summary, I suggest:

```cpp
// Regular
MyDataset::GetPath() const;

// More than one paths
MyDataset::GetPaths() const;
MyDataset::GetPaths(size_t index) const;

// Different types of paths
MyDataset::GetRGBPaths() const;
MyDataset::GetRGBPaths(size_t index) const;
MyDataset::GetDepthPaths() const;
MyDataset::GetDepthPaths(size_t index) const;
MyDataset::GetCameraTrajectoryPath() const;
MyDataset::GetCameraTrajectoryPath(size_t index) const;
```

```python
md = MyDataset()

# Regular
md.path

# More than one paths
md.paths
md.paths[index]

# Different types of paths
md.rgb_paths
md.rgb_paths[index]
md.depth_paths
md.depth_paths[index]
md.camera_trajectory_paths
md.camera_trajectory_paths[index]
```

2022-01-20 16:52 UTC, reyanshsolis commented
> > `def_property_*` cannot accept an argument, therefore it can not be used for `GetExtractDir(bool relative_to_data_root = false), GetDownloadDir(bool relative_to_data_root = false), GetPath(size index)`. So `def` is used.
> 
> Sounds good. But do we need actually need to expose `GetExtractDir` and `GetDownloadDir` in Python?
> 
> > The Path and Paths design might lead to some confusion
> 
> What is the confusion?
> 
> In summary, I suggest:
> 
> ```c++
> // Regular
> MyDataset::GetPath() const;
> 
> // More than one paths
> MyDataset::GetPaths() const;
> MyDataset::GetPaths(size_t index) const;
> 
> // Different types of paths
> MyDataset::GetRGBPaths() const;
> MyDataset::GetRGBPaths(size_t index) const;
> MyDataset::GetDepthPaths() const;
> MyDataset::GetDepthPaths(size_t index) const;
> MyDataset::GetCameraTrajectoryPath() const;
> MyDataset::GetCameraTrajectoryPath(size_t index) const;
> ```
> 
> ```python
> md = MyDataset()
> 
> # Regular
> md.path
> 
> # More than one paths
> md.paths
> md.paths[index]
> 
> # Different types of paths
> md.rgb_paths
> md.rgb_paths[index]
> md.depth_paths
> md.depth_paths[index]
> md.camera_trajectory_paths
> md.camera_trajectory_paths[index]
> ```

Sounds good. Added the required changes. I will be adding `pybind` in a separate PR soon.

2022-01-21 06:21 UTC, reyanshsolis reviewed
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4583)* status: 1 of 15 files reviewed, 3 unresolved discussions (waiting on @yxlao)

___
*[cpp/tests/geometry/PointCloud.cpp, line 1192 at r4](https://reviewable.io/reviews/isl-org/open3d/4583#-MtJHOIBhBkotxYAP9Tm-r4-1192:-MtvHl244nUFFPVYPJlK:b-mg5dbg) ([raw file](https://github.com/isl-org/open3d/blob/9c22aaf4896743d5088c293ac9a89dfffa80d915/cpp/tests/geometry/PointCloud.cpp#L1192)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

- Rename `SamplePCDFragments` -> `SampleICPPointClouds`: for the dataset with 3 point clouds
- `SamplePCDPointCloud` for `fragment.pcd`
- `SamplePLYPointCloud` for `fragment.ply`
</blockquote></details>

Done. [`SamplePCDPointCloud` and `SamplePLYPointCloud`can be added in another PR with other datasets].
___
*[cpp/tests/geometry/PointCloud.cpp, line 1209 at r5](https://reviewable.io/reviews/isl-org/open3d/4583#-Mtq0XH88yxgai0_Rc9X:-MtvHvcEBMpv_O-Lqpyk:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/98af9a1a1afbaf5050117f3ce17c51f2aaf3dc53/cpp/tests/geometry/PointCloud.cpp#L1209)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

```cpp
string MyDataset::GetPath()  const;   // If the dataset has one path
vector<string> MyDataset::GetPaths() const;  // If the dataset has more than one paths
string MyDataset::GetPaths(size_t index)  const;  // If the dataset has more than one paths

MyDataset::GetRGBPaths()  const;
MyDataset::GetDepthPaths()  const;
MyDataset::GetCameraTrajectoryPath()  const;
```

```python
md = MyDataset()
md.path  # Pybind read-only property bind to `GetPath()` function.
md.paths  # Pybind read-only property bind to `GetPaths()` function.

md.rgb_paths[5]
md.depth_paths
md.camera_trajectory_path
```

```cpp
tensor.def_property_readonly("dtype", &Tensor::GetDtype);
tensor.def_property_readonly("device", &Tensor::GetDevice);
tensor.def_property_readonly("blob", &Tensor::GetBlob);
````

Benefits for using functions:
- We don't need to create new states in class.
- Avoid public members (public members are typically bad design in C++).
- Implement logic in getter function to derive path from root.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-21 16:30 UTC, yxlao requested changes
> Reviewed 1 of 6 files at r3, 1 of 1 files at r5, 4 of 11 files at r6, 5 of 7 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4583)* status: 13 of 15 files reviewed, 15 unresolved discussions (waiting on @reyanshsolis and @yxlao)

___
*[cpp/open3d/data/Dataset.h, line 108 at r7](https://reviewable.io/reviews/isl-org/open3d/4583#-MtvZqOu9tEfuG7q4-98:-MtvZ4vj4lMzwKMucdw8:b-ds64xc) ([raw file](https://github.com/isl-org/open3d/blob/291c73820319db845c40ae4bc92c4d370257b419/cpp/open3d/data/Dataset.h#L108)):*
Here are some discussions on whether we shall implement the inherited virtual destructor. 
https://stackoverflow.com/a/2198400/1255535

> Yes, a destructor in a derived class can be omitted if it has nothing to do. And it doesn't matter whether or not its virtual.
> I would omit it if possible. 

So I think it is fine to omit it. 
___
*[cpp/open3d/data/Dataset.h, line 122 at r7](https://reviewable.io/reviews/isl-org/open3d/4583#-Mtvb7fe56o9FZEQm1iK:-Mtvb7fe56o9FZEQm1iL:bdno7wi) ([raw file](https://github.com/isl-org/open3d/blob/291c73820319db845c40ae4bc92c4d370257b419/cpp/open3d/data/Dataset.h#L122)):*
> ```objc
>                    "download/sample-icp-pointclouds/SampleICPPointClouds.zip"},
>                   "3ee7a2631caa3c47a333972e3c4fb315") {
>         for (int i = 0; i < 3; ++i) {
> ```

Is there a reason why we keep the implementation in `.h` instead of `.cpp`? I think it is fine to hind the URLs in the CPP file. 
___
*[cpp/open3d/data/Dataset.h, line 128 at r7](https://reviewable.io/reviews/isl-org/open3d/4583#-MtvbV9S4Q7ByxAxOogw:-MtvbV9S4Q7ByxAxOogx:br1hs5m) ([raw file](https://github.com/isl-org/open3d/blob/291c73820319db845c40ae4bc92c4d370257b419/cpp/open3d/data/Dataset.h#L128)):*
> ```objc
>         }
> 
>         Dataset::help_string_ = std::string(R""""(
> ```

it is possible to set `this->help_string_` in the constructor?
___
*[cpp/open3d/data/Dataset.h, line 136 at r7](https://reviewable.io/reviews/isl-org/open3d/4583#-Mtv_hByENl3KbmuIEjW:-Mtv_hByENl3KbmuIEjX:b-okz2st) ([raw file](https://github.com/isl-org/open3d/blob/291c73820319db845c40ae4bc92c4d370257b419/cpp/open3d/data/Dataset.h#L136)):*
> ```objc
> - Format: PCD Binary.
> - Source: ICL-NUIM RGBD Benchmark Dataset.
> - MD5: 4d39442a86e9fe80c967a6c513d57442
> ```

- Update md5.
- Add original download link.
- Check other docstirngs as well.
___
*[cpp/open3d/data/Dataset.h, line 146 at r7](https://reviewable.io/reviews/isl-org/open3d/4583#-MtvarRBEcjPzMnBbuwE:-MtvarRBEcjPzMnBbuwF:bkgafpg) ([raw file](https://github.com/isl-org/open3d/blob/291c73820319db845c40ae4bc92c4d370257b419/cpp/open3d/data/Dataset.h#L146)):*
> ```objc
> 
> Data Members:
>     path_to_fragments_ : List of path to PCD point-cloud fragments.
> ```

Same, update, change other docstrings as well.
___
*[cpp/open3d/data/Dataset.h, line 58 at r8](https://reviewable.io/reviews/isl-org/open3d/4583#-MtxKUIE2LzytMxfUtru:-MtxKUIF99GQKJpAAZQ5:bqk70zs) ([raw file](https://github.com/isl-org/open3d/blob/0624be218c7f01feec1c62ed4ac6397e279d9706/cpp/open3d/data/Dataset.h#L58)):*
> ```objc
> /// - When a dataset object is instantiated, the corresponding data will be
> ///   downloaded in `data_root/download/prefix/` and extracted or copied to
> ///   `data_root/extract/prefix/`. If the extracted data directory exists, the
> ```

`${data_root}`
___
*[cpp/open3d/data/Dataset.h, line 75 at r8](https://reviewable.io/reviews/isl-org/open3d/4583#-MtxKX41B5-2Spg4GlSQ:-MtxKX41B5-2Spg4GlSR:bzcekws) ([raw file](https://github.com/isl-org/open3d/blob/0624be218c7f01feec1c62ed4ac6397e279d9706/cpp/open3d/data/Dataset.h#L75)):*
> ```objc
>     ///
>     /// \param prefix Prefix of the dataset. The data is downloaded in
>     /// `open3d_root/download/prefix/` and extracted in
> ```

`${data_root}` instead of `open3d_root`. Change all. 
___
*[cpp/open3d/data/Dataset.h, line 78 at r8](https://reviewable.io/reviews/isl-org/open3d/4583#-MtxKbYt2RRxYx4aK0hb:-MtxKbYt2RRxYx4aK0hc:b-qemtjc) ([raw file](https://github.com/isl-org/open3d/blob/0624be218c7f01feec1c62ed4ac6397e279d9706/cpp/open3d/data/Dataset.h#L78)):*
> ```objc
>     /// `open3d_root/extract/prefix/`.
>     /// \param help_string Helpful documentation string related to the dataset
>     /// and available functionalities
> ```

nit: `.`
___
*[cpp/open3d/data/Dataset.h, line 103 at r8](https://reviewable.io/reviews/isl-org/open3d/4583#-MtxLU8lA_G5t2dgrJlK:-MtxLU8lA_G5t2dgrJlL:b-yxodug) ([raw file](https://github.com/isl-org/open3d/blob/0624be218c7f01feec1c62ed4ac6397e279d9706/cpp/open3d/data/Dataset.h#L103)):*
> ```objc
>     /// \param relative_to_data_root If true, the path is relative to open3d
>     /// data root, otherwise it is absolute. (Default: false).
>     const std::string GetExtractDir(
> ```

Can we always use the absolute path? Seems like only the absolute path is used besides in unit tests.
___
*[cpp/open3d/data/Dataset.h, line 111 at r8](https://reviewable.io/reviews/isl-org/open3d/4583#-MtxLRjj0p0Jkc5r6lu1:-MtxLRjj0p0Jkc5r6lu2:b-yxodug) ([raw file](https://github.com/isl-org/open3d/blob/0624be218c7f01feec1c62ed4ac6397e279d9706/cpp/open3d/data/Dataset.h#L111)):*
> ```objc
>     /// \param relative_to_data_root If true, the path is relative to open3d
>     /// data root, otherwise it is absolute. (Default: false).
>     const std::string GetDownloadDir(
> ```

Can we always use the absolute path? Seems like only the absolute path is used besides in unit tests.
___
*[cpp/open3d/data/Dataset.h, line 206 at r8](https://reviewable.io/reviews/isl-org/open3d/4583#-MtxSyGsDMnotxA2wntz:-MtxSyGsDMnotxA2wnu-:bqd4zaq) ([raw file](https://github.com/isl-org/open3d/blob/0624be218c7f01feec1c62ed4ac6397e279d9706/cpp/open3d/data/Dataset.h#L206)):*
> ```objc
>     // path_to_pointclouds_[x] returns path to `cloud_bin_x.pcd` where x is from
>     // 0 to 2.
>     std::vector<std::string> path_to_pointclouds_;
> ```

When we have `GetPaths()`, the underlying member shall be consistently named, i.e. `paths_`. 
___
*[cpp/open3d/data/Dataset.h, line 232 at r8](https://reviewable.io/reviews/isl-org/open3d/4583#-MtxMBkC66Z-wOYnwX5d:-MtxMBkC66Z-wOYnwX5e:b-t6o5vh) ([raw file](https://github.com/isl-org/open3d/blob/0624be218c7f01feec1c62ed4ac6397e279d9706/cpp/open3d/data/Dataset.h#L232)):*
> ```objc
>         }
> 
>         Dataset::help_string_ = std::string(R""""(
> ```

Does it work if we use 3 quotes instead of 4? Change other quotes as well. 
___
*[cpp/open3d/data/Dataset.h, line 284 at r8](https://reviewable.io/reviews/isl-org/open3d/4583#-MtxRZ5REec_Ocw-L1sC:-MtxRZ5REec_Ocw-L1sD:bej2kuk) ([raw file](https://github.com/isl-org/open3d/blob/0624be218c7f01feec1c62ed4ac6397e279d9706/cpp/open3d/data/Dataset.h#L284)):*
> ```objc
>     RedwoodOfficeFragments(const std::string& prefix = "RedwoodOfficeFragments",
>                            const std::string& data_root = "")
>         : SimpleDataset(prefix,
> ```

- Move the constructor to `.cpp` file. 
- We can also change `helper_string_` to a function. Where the function will return the string description plus information about the URL, MD5, etc.


<!-- Sent from Reviewable.io -->

2022-01-22 00:08 UTC, reyanshsolis commented
Without `virtual destructor`, I am getting the following error in `pybind`

```bash
In file included from /home/rey/workspace/isl/data_manager/Open3D/build/_deps/ext_pybind11-src/include/pybind11/numpy.h:12,
                 from /home/rey/workspace/isl/data_manager/Open3D/build/_deps/ext_pybind11-src/include/pybind11/eigen.h:12,
                 from /home/rey/workspace/isl/data_manager/Open3D/cpp/pybind/../pybind/open3d_pybind.h:45,
                 from /home/rey/workspace/isl/data_manager/Open3D/cpp/pybind/../pybind/data/data.h:29,
                 from /home/rey/workspace/isl/data_manager/Open3D/cpp/pybind/data/dataset.cpp:31:
/home/rey/workspace/isl/data_manager/Open3D/build/_deps/ext_pybind11-src/include/pybind11/pybind11.h: In instantiation of ‘class pybind11::class_<open3d::data::dataset::SampleICPPointClouds, open3d::data::PySimpleDataset<open3d::data::dataset::SampleICPPointClouds>, std::shared_ptr<open3d::data::dataset::SampleICPPointClouds>, open3d::data::SimpleDataset>’:
/home/rey/workspace/isl/data_manager/Open3D/cpp/pybind/data/dataset.cpp:42:36:   required from here
/home/rey/workspace/isl/data_manager/Open3D/build/_deps/ext_pybind11-src/include/pybind11/pybind11.h:1260:30: error: static assertion failed: Cannot use an alias class with a non-polymorphic type
 1260 |     static_assert(!has_alias || std::is_polymorphic<type>::value,
      |                   ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/rey/workspace/isl/data_manager/Open3D/build/_deps/ext_pybind11-src/include/pybind11/pybind11.h: In instantiation of ‘class pybind11::class_<open3d::data::dataset::RedwoodLivingRoomFragments, open3d::data::PySimpleDataset<open3d::data::dataset::RedwoodLivingRoomFragments>, std::shared_ptr<open3d::data::dataset::RedwoodLivingRoomFragments>, open3d::data::SimpleDataset>’:
/home/rey/workspace/isl/data_manager/Open3D/cpp/pybind/data/dataset.cpp:63:21:   required from here
/home/rey/workspace/isl/data_manager/Open3D/build/_deps/ext_pybind11-src/include/pybind11/pybind11.h:1260:30: error: static assertion failed: Cannot use an alias class with a non-polymorphic type
/home/rey/workspace/isl/data_manager/Open3D/build/_deps/ext_pybind11-src/include/pybind11/pybind11.h: In instantiation of ‘class pybind11::class_<open3d::data::dataset::RedwoodOfficeFragments, open3d::data::PySimpleDataset<open3d::data::dataset::RedwoodOfficeFragments>, std::shared_ptr<open3d::data::dataset::RedwoodOfficeFragments>, open3d::data::SimpleDataset>’:
/home/rey/workspace/isl/data_manager/Open3D/cpp/pybind/data/dataset.cpp:83:38:   required from here
/home/rey/workspace/isl/data_manager/Open3D/build/_deps/ext_pybind11-src/include/pybind11/pybind11.h:1260:30: error: static assertion failed: Cannot use an alias class with a non-polymorphic type
make[3]: *** [cpp/pybind/CMakeFiles/pybind.dir/build.make:328: cpp/pybind/CMakeFiles/pybind.dir/data/dataset.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /home/rey/workspace/isl/data_manager/Open3D/build/_deps/ext_pybind11-src/include/pybind11/numpy.h:12,
                 from /home/rey/workspace/isl/data_manager/Open3D/build/_deps/ext_pybind11-src/include/pybind11/eigen.h:12,
                 from /home/rey/workspace/isl/data_manager/Open3D/cpp/pybind/../pybind/open3d_pybind.h:45,
                 from /home/rey/workspace/isl/data_manager/Open3D/cpp/pybind/../pybind/data/data.h:29,
                 from /home/rey/workspace/isl/data_manager/Open3D/cpp/pybind/data/data.cpp:27:
/home/rey/workspace/isl/data_manager/Open3D/build/_deps/ext_pybind11-src/include/pybind11/pybind11.h: In instantiation of ‘class pybind11::class_<open3d::data::Dataset, open3d::data::PyDataset<open3d::data::Dataset>, std::shared_ptr<open3d::data::Dataset> >’:
/home/rey/workspace/isl/data_manager/Open3D/cpp/pybind/data/data.cpp:40:13:   required from here
/home/rey/workspace/isl/data_manager/Open3D/build/_deps/ext_pybind11-src/include/pybind11/pybind11.h:1260:30: error: static assertion failed: Cannot use an alias class with a non-polymorphic type
 1260 |     static_assert(!has_alias || std::is_polymorphic<type>::value,
      |                   ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/rey/workspace/isl/data_manager/Open3D/build/_deps/ext_pybind11-src/include/pybind11/pybind11.h: In instantiation of ‘class pybind11::class_<open3d::data::SimpleDataset, open3d::data::PySimpleDataset<open3d::data::SimpleDataset>, std::shared_ptr<open3d::data::SimpleDataset>, open3d::data::Dataset>’:
/home/rey/workspace/isl/data_manager/Open3D/cpp/pybind/data/data.cpp:57:28:   required from here
/home/rey/workspace/isl/data_manager/Open3D/build/_deps/ext_pybind11-src/include/pybind11/pybind11.h:1260:30: error: static assertion failed: Cannot use an alias class with a non-polymorphic type
make[3]: *** [cpp/pybind/CMakeFiles/pybind.dir/build.make:314: cpp/pybind/CMakeFiles/pybind.dir/data/data.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:4165: cpp/pybind/CMakeFiles/pybind.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:4250: cpp/pybind/CMakeFiles/install-pip-package.dir/rule] Error 2
make: *** [Makefile:1157: install-pip-package] Error 2
```

Anyways it is removed from this PR. If required can be added back in the `pybind` PR.

2022-01-24 17:50 UTC, yxlao commented
Remaining comment: avoid hard-coded URL/MD5 in the help_string.

2022-01-24 17:50 UTC, merged