Add docker GUI instructions
isl-org/Open3D pull request #4671
Opened 2022-01-29 23:15 UTC by ssheorey

2022-01-31 02:46 UTC, yxlao requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4671)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @errissa and @ssheorey)

___
*[docs/getting_started.rst.in, line 147 at r1](https://reviewable.io/reviews/isl-org/open3d/4671#-Mui-QlJ0BboxabSppW8:-Mui-QlJ0BboxabSppW9:b-5whj8b) ([raw file](https://github.com/isl-org/open3d/blob/d28705ffa4de7c3419f25eb2e321d5708679b0f6/docs/getting_started.rst.in#L147)):*
> ```
> 2. X server:
>     :bash:`-v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY`
> ```

It would be more intuitive if we provide an end-to-end example with all commands to run, showcasing how to draw a basic geometry inside docker. 


<!-- Sent from Reviewable.io -->

2022-01-31 03:44 UTC, errissa requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4671)* status: all files reviewed, 1 unresolved discussion (waiting on @yxlao)

___
*[docs/getting_started.rst.in, line 147 at r1](https://reviewable.io/reviews/isl-org/open3d/4671#-Mui-QlJ0BboxabSppW8:-MuiDJao4H0Tpl2CQ1Sb:b-yz1u1e) ([raw file](https://github.com/isl-org/open3d/blob/d28705ffa4de7c3419f25eb2e321d5708679b0f6/docs/getting_started.rst.in#L147)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

It would be more intuitive if we provide an end-to-end example with all commands to run, showcasing how to draw a basic geometry inside docker. 
</blockquote></details>

I concur. If I didn't already know how to run Open3D from Docker I'm no sure these instructions are enough to get it correct. Also, is it not necessary to run `xhost +` on the host in order for apps within docker to be able to access host X server?


<!-- Sent from Reviewable.io -->

2022-01-31 06:50 UTC, ssheorey reviewed
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4671)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @errissa and @yxlao)

___
*[docs/getting_started.rst.in, line 147 at r1](https://reviewable.io/reviews/isl-org/open3d/4671#-Mui-QlJ0BboxabSppW8:-MuisB5J6XIIQH_EbmRk:b-s0e726) ([raw file](https://github.com/isl-org/open3d/blob/d28705ffa4de7c3419f25eb2e321d5708679b0f6/docs/getting_started.rst.in#L147)):*
<details><summary><i>Previously, errissa (Rene) wrote…</i></summary><blockquote>

I concur. If I didn't already know how to run Open3D from Docker I'm no sure these instructions are enough to get it correct. Also, is it not necessary to run `xhost +` on the host in order for apps within docker to be able to access host X server?
</blockquote></details>

Done.

Added complete example that containerizes the Open3D viewer. Drawing geometry is covered in other places.


<!-- Sent from Reviewable.io -->

2022-01-31 11:00 UTC, yxlao requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4671)* status: all files reviewed, 3 unresolved discussions (waiting on @errissa, @ssheorey, and @yxlao)

___
*[docs/getting_started.rst.in, line 174 at r2](https://reviewable.io/reviews/isl-org/open3d/4671#-Mujm9ym2oC5yZT3nDqz:-Mujm9ym2oC5yZT3nDr-:b-ymiq2f) ([raw file](https://github.com/isl-org/open3d/blob/fd67b9a559fa45f78586eb98ebb00a8c056332f9/docs/getting_started.rst.in#L174)):*
> ```
> 
>     # Copy and install Open3D viewer from docker context
>     COPY open3d-app-*.deb /root/
> ```

Could we mention how to get the `.deb` file.
___
*[docs/getting_started.rst.in, line 201 at r2](https://reviewable.io/reviews/isl-org/open3d/4671#-MujmG3M9hyQjFj8DQrY:-MujmG3M9hyQjFj8DQrZ:b-yv7woi) ([raw file](https://github.com/isl-org/open3d/blob/fd67b9a559fa45f78586eb98ebb00a8c056332f9/docs/getting_started.rst.in#L201)):*
> ```
> 
> .. code-block:: bash
> ```

Could we include how to create the Dockerfile here?

```
wget https://xxx/xxx/open3d-xxxx.deb
echo -e "FROM ubuntu:latest \nCOPY xxx ....\n" >> Dockerfile
```

That is, it would be ideal if copy-and-paste all commands can successfully launch the visualizer in Docker.


<!-- Sent from Reviewable.io -->

2022-01-31 16:44 UTC, ssheorey reviewed
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4671)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @errissa and @yxlao)

___
*[docs/getting_started.rst.in, line 174 at r2](https://reviewable.io/reviews/isl-org/open3d/4671#-Mujm9ym2oC5yZT3nDqz:-Mul0QZ9E0eq5htTCivI:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/fd67b9a559fa45f78586eb98ebb00a8c056332f9/docs/getting_started.rst.in#L174)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Could we mention how to get the `.deb` file.
</blockquote></details>

Done.
___
*[docs/getting_started.rst.in, line 201 at r2](https://reviewable.io/reviews/isl-org/open3d/4671#-MujmG3M9hyQjFj8DQrY:-Mul0SZM-YOvxVtR4hLn:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/fd67b9a559fa45f78586eb98ebb00a8c056332f9/docs/getting_started.rst.in#L201)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Could we include how to create the Dockerfile here?

```
wget https://xxx/xxx/open3d-xxxx.deb
echo -e "FROM ubuntu:latest \nCOPY xxx ....\n" >> Dockerfile
```

That is, it would be ideal if copy-and-paste all commands can successfully launch the visualizer in Docker.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-01 19:06 UTC, errissa approved these changes
LGTM

2022-02-01 21:40 UTC, yxlao approved these changes

2022-02-01 21:40 UTC, merged