Add docs for python examples
isl-org/Open3D pull request #4703
Opened 2022-02-04 16:11 UTC by ShreyanshDarshan

2022-02-04 20:11 UTC, yxlao requested changes
> Reviewed 4 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4703)* status: all files reviewed, 3 unresolved discussions (waiting on @ShreyanshDarshan and @yxlao)

___
*[docs/index.rst, line 82 at r2](https://reviewable.io/reviews/isl-org/open3d/4703#-Mv5M3Rq9xexSF-nBwNK:-Mv5M3Rq9xexSF-nBwNL:b-kf0cta) ([raw file](https://github.com/isl-org/open3d/blob/fdb62298f825d6255974246bdc6af5f8ff48052f/docs/index.rst#L82)):*
> ```reStructuredText
>     python_api/open3d.visualization
> 
> .. toctree::
> ```

I have moved the python examples to the bottom since the sidebar is too long. We'll revisit this to simplify our sidebar contents.
___
*[docs/make_docs.py, line 47 at r2](https://reviewable.io/reviews/isl-org/open3d/4703#-Mv5L6zEAhPsDdE2NNtF:-Mv5L6zEAhPsDdE2NNtG:b-ew5lp5) ([raw file](https://github.com/isl-org/open3d/blob/fdb62298f825d6255974246bdc6af5f8ff48052f/docs/make_docs.py#L47)):*
> ```Python
> import urllib.request
> 
> root_dir_path = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
> ```

We already have `pwd = os.path.dirname(os.path.realpath(__file__))`

Therefore, we can do the `from cli import` inside the `PyExampleDocsBuilder`'s init function.
___
*[docs/make_docs.py, line 349 at r2](https://reviewable.io/reviews/isl-org/open3d/4703#-Mv5LXCvDRyjXeq1hG1y:-Mv5LXCvDRyjXeq1hG1z:bimexyc) ([raw file](https://github.com/isl-org/open3d/blob/fdb62298f825d6255974246bdc6af5f8ff48052f/docs/make_docs.py#L349)):*
> ```Python
>                 if (cat.stem == "geometry"):
>                     self._generate_index(cat.stem.capitalize(), out_dir)
>                     with open(out_dir / "index.rst", "a") as f:
> ```

Can we change `Io` to `IO` in the title for IO?


<!-- Sent from Reviewable.io -->

2022-02-05 05:49 UTC, ShreyanshDarshan reviewed
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4703)* status: all files reviewed, 3 unresolved discussions (waiting on @yxlao)

___
*[docs/make_docs.py, line 47 at r2](https://reviewable.io/reviews/isl-org/open3d/4703#-Mv5L6zEAhPsDdE2NNtF:-Mv7Q5Sz9-ylf_ZT0N9u:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/fdb62298f825d6255974246bdc6af5f8ff48052f/docs/make_docs.py#L47)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

We already have `pwd = os.path.dirname(os.path.realpath(__file__))`

Therefore, we can do the `from cli import` inside the `PyExampleDocsBuilder`'s init function.
</blockquote></details>

Done.
___
*[docs/make_docs.py, line 349 at r2](https://reviewable.io/reviews/isl-org/open3d/4703#-Mv5LXCvDRyjXeq1hG1y:-Mv7Q9PC1CbVP0cmx00r:b-osq187) ([raw file](https://github.com/isl-org/open3d/blob/fdb62298f825d6255974246bdc6af5f8ff48052f/docs/make_docs.py#L349)):*
<details><summary><i>Previously, yxlao (Yixing Lao) wrote…</i></summary><blockquote>

Can we change `Io` to `IO` in the title for IO?
</blockquote></details>

Would it be better to hardcode the capitalised names of all the categories or should we treat IO as an exception here?


<!-- Sent from Reviewable.io -->

2022-02-05 06:27 UTC, yxlao requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/4703)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ShreyanshDarshan and @yxlao)

___
*[docs/make_docs.py, line 349 at r2](https://reviewable.io/reviews/isl-org/open3d/4703#-Mv5LXCvDRyjXeq1hG1y:-Mv7YxeU1kEsTHtMdSc9:byogh3v) ([raw file](https://github.com/isl-org/open3d/blob/fdb62298f825d6255974246bdc6af5f8ff48052f/docs/make_docs.py#L349)):*
<details><summary><i>Previously, ShreyanshDarshan (Shreyansh Darshan) wrote…</i></summary><blockquote>

Would it be better to hardcode the capitalised names of all the categories or should we treat IO as an exception here?
</blockquote></details>

I've thought about that as well. 

IO is kind of special. It is strange to see `Io`. But making everything all capitalized seems to be too much. As it is just documentation here, so I think it's fine to make it a special case.


<!-- Sent from Reviewable.io -->

2022-02-07 18:25 UTC, yxlao approved these changes

2022-02-08 02:41 UTC, merged