Add some legacy warppers for Tensor PointCloud
isl-org/Open3D pull request #5330
Opened 2022-07-19 10:55 UTC by yuecideng

This PR adds wrapper for `FarthestPointDownSample`, `HiddenPointRemoval` and `SegmentPlane` to tensor PointCloud.

2022-07-29 00:29 UTC, yxlao approved these changes

2022-07-29 00:30 UTC, yxlao commented on cpp/tests/t/geometry/PointCloud.cpp
> +    if (!device.IsCPU()) {
For non-CPU point cloud, we shall first copy to host, process, and copy back.

2022-07-29 05:05 UTC, ssheorey requested changes
For all wrappers over legacy functions, mention in both C++ and Python docs that only CPU device is supported and CUDA data will be copied to the CPU for processing. Also mention which attributes are preserved by the operation. 

In pybind code, document return values and add a brief example. See cluster dbscan as an example.

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5330#-:-N87DkAe1jhvHuyQ7Zl5:blegu8p)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @reyanshsolis and @yuecideng)

___
*[`cpp/open3d/t/geometry/PointCloud.h` line 402 at r3](https://reviewable.io/reviews/isl-org/open3d/5330#-N87J4QU854wChobJjWD:-N87J4QU854wChobJjWE:boqu38e) ([raw file](https://github.com/isl-org/open3d/blob/425d2c1df3e81a52ef3b259f8bbc1a7b370340c6/cpp/open3d/t/geometry/PointCloud.h#L402)):*
> ```objc
>     /// \param camera_location All points not visible from that location will be
>     /// removed.
>     /// \param radius The radius of the spherical projection.
> ```

Add docs for return value (\return)
___
*[`cpp/open3d/t/geometry/PointCloud.cpp` line 858 at r3](https://reviewable.io/reviews/isl-org/open3d/5330#-N87IkjH1VvdPWvGPF3Q:-N87IkjH1VvdPWvGPF3R:b-owv2yn) ([raw file](https://github.com/isl-org/open3d/blob/425d2c1df3e81a52ef3b259f8bbc1a7b370340c6/cpp/open3d/t/geometry/PointCloud.cpp#L858)):*
> ```cpp
>             TriangleMesh::FromLegacy(*lmesh, GetPointPositions().GetDtype(),
>                                      core::Int64, GetDevice()),
>             core::Tensor(indices, {(int64_t)indices.size()}, core::Int64,
> ```

Use `core::Tensor(std::move(indices)).To(GetDevice())` (Tensor ctor that takes ownership of vector data). This will prevent a copy if data is on the CPU. 

Since we know the indices of the retained points, copy over all point attributes for the retained points.
___
*[`cpp/open3d/t/geometry/PointCloud.cpp` line 892 at r3](https://reviewable.io/reviews/isl-org/open3d/5330#-N87I0zgEFL3M3UkiRNA:-N87I0zh5xqGXki73_mV:b231935) ([raw file](https://github.com/isl-org/open3d/blob/425d2c1df3e81a52ef3b259f8bbc1a7b370340c6/cpp/open3d/t/geometry/PointCloud.cpp#L892)):*
> ```cpp
>     return std::make_tuple(
>             core::eigen_converter::EigenMatrixToTensor(plane).Flatten(),
>             core::Tensor(indices, {(int64_t)indices.size()}, core::Int64,
> ```

Use `core::Tensor(std::move(indices)).To(GetDevice())` (Tensor ctor that takes ownership of vector data). This will prevent a copy if data is on the CPU. 


<!-- Sent from Reviewable.io -->

2022-07-29 07:47 UTC, yuecideng reviewed
I tried to update the docs in pybind file. Please see whether it is acceptable.

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5330#-:-N87uYT03MGkYHkv_rL2:bz573ss)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @reyanshsolis, @ssheorey, and @yuecideng)

___
*[`cpp/open3d/t/geometry/PointCloud.h` line 402 at r3](https://reviewable.io/reviews/isl-org/open3d/5330#-N87J4QU854wChobJjWD:-N87T67A4dK1xuLsDaUr:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/425d2c1df3e81a52ef3b259f8bbc1a7b370340c6/cpp/open3d/t/geometry/PointCloud.h#L402)):*
<details><summary><i>Previously, ssheorey (Sameer Sheorey) wrote…</i></summary><blockquote>

Add docs for return value (\return)
</blockquote></details>

Done.
___
*[`cpp/open3d/t/geometry/PointCloud.cpp` line 858 at r3](https://reviewable.io/reviews/isl-org/open3d/5330#-N87IkjH1VvdPWvGPF3Q:-N87U9G63OdzYdN8zeIA:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/425d2c1df3e81a52ef3b259f8bbc1a7b370340c6/cpp/open3d/t/geometry/PointCloud.cpp#L858)):*
<details><summary><i>Previously, ssheorey (Sameer Sheorey) wrote…</i></summary><blockquote>

Use `core::Tensor(std::move(indices)).To(GetDevice())` (Tensor ctor that takes ownership of vector data). This will prevent a copy if data is on the CPU. 

Since we know the indices of the retained points, copy over all point attributes for the retained points.
</blockquote></details>

Done.
___
*[`cpp/open3d/t/geometry/PointCloud.cpp` line 892 at r3](https://reviewable.io/reviews/isl-org/open3d/5330#-N87I0zgEFL3M3UkiRNA:-N87UA7FD2_MNoYoZ458:b-896fix) ([raw file](https://github.com/isl-org/open3d/blob/425d2c1df3e81a52ef3b259f8bbc1a7b370340c6/cpp/open3d/t/geometry/PointCloud.cpp#L892)):*
<details><summary><i>Previously, ssheorey (Sameer Sheorey) wrote…</i></summary><blockquote>

Use `core::Tensor(std::move(indices)).To(GetDevice())` (Tensor ctor that takes ownership of vector data). This will prevent a copy if data is on the CPU. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-05 14:44 UTC, reyanshsolis approved these changes

2022-08-12 15:16 UTC, yxlao approved these changes

2022-08-12 15:16 UTC, merged