Fix raycasting scene: Allow setting of number of threads that are used for building a raycasting scene
isl-org/Open3D pull request #5384
Opened 2022-07-30 20:50 UTC by jjabo

This PR adds an argument to the constructor of RaycastingScene to allow the user to control the number of threads that are used for building a RaycastingScene. It completes the intention of PR #4100, where the user was enabled to control the number of threads for doing computations in a RaycastingScene.

Currently all hardware threads are used for building a RaycastingScene, since a `RTCDevice` is created using this: `rtcNewDevice(NULL)`. This is unwanted behavior and can lead to problems, e.g. if many cores are present (>=16), and the scene is not huge, using all hardware threads results actually in a slowdown.

2022-07-31 05:24 UTC, ssheorey commented
@yxlao I think it would be valuable for user control over the number of threads that Open3D uses overall for all operations (including CPU Tensor ops).

2022-07-31 05:42 UTC, benjaminum requested changes
@jjabo Good contribution. I suggest some minor changes before we can merge. Please see the comments.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5384#-:-N8HlNxP-JI48VtnVZti:bwgt7pk)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @jjabo and @yxlao)

___
*[`cpp/open3d/t/geometry/RaycastingScene.h` line 52 at r1](https://reviewable.io/reviews/isl-org/open3d/5384#-N8Hjgq95b1XdDXNauow:-N8Hjgq95b1XdDXNauox:bt1u7e2) ([raw file](https://github.com/isl-org/open3d/blob/34f183c00b95b65b50fef72f6057a3db48ce8ec8/cpp/open3d/t/geometry/RaycastingScene.h#L52)):*
> ```objc
> public:
>     /// \brief Default Constructor.
>     RaycastingScene(int64_t build_threads = 0);
> ```

To be consistent with the other functions, please change the argument name to `nthreads` and explain the new argument in the docstring (its effect on AddTriangles).
___
*[`cpp/pybind/t/geometry/raycasting_scene.cpp` line 72 at r1](https://reviewable.io/reviews/isl-org/open3d/5384#-N8Hkn5pAnJfYpTyUmUi:-N8Hkn5pAnJfYpTyUmUj:budewm4) ([raw file](https://github.com/isl-org/open3d/blob/34f183c00b95b65b50fef72f6057a3db48ce8ec8/cpp/pybind/t/geometry/raycasting_scene.cpp#L72)):*
> ```cpp
>     # Visualize the hit distance (depth)
>     plt.imshow(ans['t_hit'].numpy())
> ```

For python add the description of the new argument to the class docstring.
___
*[`cpp/pybind/t/geometry/raycasting_scene.cpp` line 77 at r1](https://reviewable.io/reviews/isl-org/open3d/5384#-N8Hkgh_D0QmTG8M76Vn:-N8Hkgh_D0QmTG8M76Vo:b-jxcaaj) ([raw file](https://github.com/isl-org/open3d/blob/34f183c00b95b65b50fef72f6057a3db48ce8ec8/cpp/pybind/t/geometry/raycasting_scene.cpp#L77)):*
> ```cpp
>     // Constructors.
>     raycasting_scene.def(py::init<int64_t>(),
>                          "build_threads"_a = 0);
> ```

same here, please rename to `nthreads`


<!-- Sent from Reviewable.io -->

2022-07-31 07:52 UTC, jjabo commented
Done. I renamed the parameter to `nthreads` and added the requested documentation.

2022-08-01 09:46 UTC, benjaminum reviewed
Looks good. The only thing missing is to fix the style-check. Can you apply the style with the `apply-style` target?

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5384#-:-N8NmpET5i4bAdAlmmJs:b3shsqg)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @benjaminum, @jjabo, and @yxlao)



<!-- Sent from Reviewable.io -->

2022-08-01 10:48 UTC, jbotsch-fy commented
Alright, `apply-style` is done :)

2022-08-01 18:16 UTC, benjaminum approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5384#-:-N8Pbvc-AALCH6n2B03G:bnfp4nl)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @benjaminum, @jjabo, and @yxlao)



<!-- Sent from Reviewable.io -->

2022-08-01 22:38 UTC, merged