Support CUDA 12.0 build.
isl-org/Open3D pull request #5833
Opened 2023-01-05 11:11 UTC by NobuoTsukamoto

Fix #5827.

Fix the build error below.
1. error: namespace "thrust" has no member "device"
2. *** No rule to make target '/usr/local/cuda/lib64/liblapack_static.a'

2023-01-19 00:08 UTC, theNded requested changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5833)* status: all files reviewed, 1 unresolved discussion (waiting on @NobuoTsukamoto and @yxlao)

___
*[`3rdparty/find_dependencies.cmake` line 1691 at r2](https://reviewable.io/reviews/isl-org/open3d/5833#-NM6KeZxClQDE73hj3Zk:-NM6KeZy3Te_DWSfO8ZT:bdbau3c) ([raw file](https://github.com/isl-org/open3d/blob/0b0ba6d4e390d37630afa8ad98918341aa25ae19/3rdparty/find_dependencies.cmake#L1691)):*
> ```CMake
>         target_link_libraries(3rdparty_cublas INTERFACE
>             CUDA::cusolver_static
>             ${CUDAToolkit_LIBRARY_DIR}/libcusolver_lapack_static.a
> ```

This removal seems not backward compatible, see [changelog](https://docs.nvidia.com/cuda/cusolver/#link-third-party-lapack-library). @yxlao should we add a version switcher?


<!-- Sent from Reviewable.io -->

2023-01-19 12:54 UTC, NobuoTsukamoto commented
CUDA 10.1 does not have libcusolver_lapack_static.a. This causes build errors.
Add switcher by CUDA version.

2023-01-19 15:58 UTC, theNded commented
> CUDA 10.1 does not have libcusolver_lapack_static.a. This causes build errors. Add switcher by CUDA version.

Could you please push the changes?

2023-01-20 16:00 UTC, yxlao commented
Yes, as @theNded suggests, we need to add a version switcher in cmake

2023-01-21 07:53 UTC, NobuoTsukamoto commented
@theNded , @yxlao 

Added CUDA version switcher to `find_dependencies.cmake`.

I have confirmed that it can be built with the following nvidia/cuda docker image.

- nvidia/cuda:10.1-devel-ubuntu18.04
- nvidia/cuda:11.7.1-devel-ubuntu22.04
- nvidia/cuda:12.0.0-devel-ubuntu22.04

I didn't add macro switcher to CUDAHashBackendBuffer.cu (e.g. CUDART_VERSION)
. This is because `cuda_runtime_api.h`, `cuda.h`, etc. must be included, and it can be built with cuda 10 and 11.

2023-01-21 16:24 UTC, theNded approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/isl-org/open3d/5833)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yxlao)



<!-- Sent from Reviewable.io -->

2023-01-23 05:03 UTC, merged