Add IO for NPZ files for Tensor-based TriangleMeshes
isl-org/Open3D pull request #6019
Opened 2023-03-21 15:24 UTC by errissa

The following script tests the basic functionality:
```
import open3d as o3d

# Load OBJ file
d = o3d.data.MonkeyModel()
mesh = o3d.t.io.read_triangle_mesh(d.path)
print(mesh)
o3d.visualization.draw(mesh)

# Save mesh as NPZ and reload it
o3d.t.io.write_triangle_mesh('monkey.npz', mesh)
mesh_npz = o3d.t.io.read_triangle_mesh('monkey.npz')
print(mesh_npz)

# Verify it looks correct
o3d.visualization.draw(mesh_npz)
```

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/isl-org/Open3D/6019)

2023-03-22 04:41 UTC, errissa commented
Texture maps are now supported. Try this updated script:
```
import open3d as o3d

# Load OBJ file
d = o3d.data.MonkeyModel()
mesh = o3d.t.io.read_triangle_mesh(d.path)
mesh.material.set_default_properties()
mesh.material.texture_maps['albedo'] = o3d.t.io.read_image(d.path_map['albedo'])

print(mesh)
o3d.visualization.draw(mesh)

# Save mesh as NPZ and reload it
o3d.t.io.write_triangle_mesh('monkey.npz', mesh)
mesh_npz = o3d.t.io.read_triangle_mesh('monkey.npz')
print(mesh_npz)

# Verify it looks correct
o3d.visualization.draw(mesh_npz)
```

2023-03-22 14:17 UTC, benjaminum requested changes
> *[Reviewable](https://reviewable.io/reviews/isl-org/Open3D/6019)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @errissa)

___
*[`cpp/open3d/t/io/TriangleMeshIO.cpp` line 243 at r2](https://reviewable.io/reviews/isl-org/Open3D/6019#-NR8c7e05uilXtfqPi6Q:-NR8c7e05uilXtfqPi6R:bcw5y9w) ([raw file](https://github.com/isl-org/Open3D/blob/1778277579b32aa7dbce00aa117034f83c446096/cpp/open3d/t/io/TriangleMeshIO.cpp#L243)):*
> ```cpp
>     }
>     if (mesh.HasTriangleAttr("texture_uvs")) {
>         mesh_attributes["uvmap"] = mesh.GetTriangleAttr("texture_uvs");
> ```

Maybe we want to change this one. 
I think the options we have are
`triangle_texture_uvs` (+valid identifier -multiple underscores)
`triangle.texture_uvs` (+like accessing an o3d attribute -can be saved to npz but not a valid identifier)
`triangle__texture_uvs` (+valid identifier -even more _)

More options after TriangleMesh->Mesh
`face{_,.,__}texture_uvs`

What do you think? @errissa 


<!-- Sent from Reviewable.io -->

2023-03-23 13:55 UTC, errissa commented
> > _[Reviewable](https://reviewable.io/reviews/isl-org/Open3D/6019)_ status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @errissa)
> 
> _[`cpp/open3d/t/io/TriangleMeshIO.cpp` line 243 at r2](https://reviewable.io/reviews/isl-org/Open3D/6019#-NR8c7e05uilXtfqPi6Q:-NR8c7e05uilXtfqPi6R:bcw5y9w) ([raw file](https://github.com/isl-org/Open3D/blob/1778277579b32aa7dbce00aa117034f83c446096/cpp/open3d/t/io/TriangleMeshIO.cpp#L243)):_
> 
> > ```c++
> >     }
> >     if (mesh.HasTriangleAttr("texture_uvs")) {
> >         mesh_attributes["uvmap"] = mesh.GetTriangleAttr("texture_uvs");
> > ```
> 
> Maybe we want to change this one. I think the options we have are `triangle_texture_uvs` (+valid identifier -multiple underscores) `triangle.texture_uvs` (+like accessing an o3d attribute -can be saved to npz but not a valid identifier) `triangle__texture_uvs` (+valid identifier -even more _)
> 
> More options after TriangleMesh->Mesh `face{_,.,__}texture_uvs`
> 
> What do you think? @errissa

I thought we might want to change this one. It doesn't fit any other patterns we're using. I think the simplest is `triangle_texture_uvs` which is consistent with the way we name everything else. I have made the change.

2023-03-24 06:35 UTC, benjaminum approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/isl-org/Open3D/6019#-:-NRHK1V1469VbuNPDOxx:bnfp4nl)* status: 0 of 3 files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2023-03-24 15:24 UTC, merged