Write directly to GLB from TGeometries
isl-org/Open3D pull request #6404
Opened 2023-10-03 01:45 UTC by errissa

Still working on getting textures embedded into GLB so not ready yet for final review.

2023-10-06 01:22 UTC, errissa commented on cpp/open3d/t/io/file_format/FileASSIMP.cpp
> +        ai_mesh->mFaces[i].mIndices = new unsigned int[3];  // triangles
Assimp `delete`s the `mIndices`. This is the allocation pattern Assimp expects.

2023-10-06 04:44 UTC, ssheorey commented on cpp/open3d/t/io/file_format/FileASSIMP.cpp
> +        ai_mesh->mFaces[i].mIndices = new unsigned int[3];  // triangles
That's unfortunate (lots of tiny mallocs is really inefficient). A comment about this would be useful in our code.

2023-10-06 13:57 UTC, errissa commented on cpp/open3d/t/io/file_format/FileASSIMP.cpp
> +    auto ai_scene = new aiScene;
Done.

2023-10-06 14:13 UTC, errissa commented on cpp/open3d/t/io/file_format/FileASSIMP.cpp
> +        return false;
Unfortunately not - only for importing.

2023-10-06 14:39 UTC, errissa commented on cpp/open3d/t/io/file_format/FileASSIMP.cpp
> +                                  const bool print_progress) {
Yes. Was already implemented checking for the presence of those properties in the TriangleMesh but I've added checks for the input flags as well.

2023-10-18 00:19 UTC, errissa commented on cpp/open3d/t/io/file_format/FileASSIMP.cpp
> +                ai_mesh->mColors[0][i].a = 1.0f;
Done.

2023-10-31 15:36 UTC, ssheorey requested changes
Looks good. 2 minor comments and we can merge.

2023-10-31 15:36 UTC, ssheorey commented on cpp/open3d/t/io/file_format/FileASSIMP.cpp
> +            mesh.GetTriangleIndices().Contiguous().To(core::Dtype::UInt32);
`.To().Contiguous()`  saves one copy for non-contiguous int64 data.

2023-10-31 15:36 UTC, ssheorey commented on cpp/open3d/t/io/file_format/FileASSIMP.cpp
Move all internal Open3D (non API) functions to an unnamed namespace (or mark as static) to avoid symbol leakage.

2023-11-01 14:52 UTC, errissa commented on cpp/open3d/t/io/file_format/FileASSIMP.cpp
Done. There was only a single function that needed to be marked static.

2023-11-01 15:43 UTC, ssheorey approved these changes

2023-11-01 21:57 UTC, merged