fixed typo
isl-org/Open3D pull request #6630
Opened 2024-02-01 12:37 UTC by mone27

Fix typo

## Type

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #
-   [ ] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context

fix typo

## Checklist:

-   [x] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

## Description

fix typo in voxelgrid python documentation

2024-02-01 15:57 UTC, saurabheights requested changes

2024-02-01 15:57 UTC, saurabheights commented on cpp/pybind/geometry/voxelgrid.cpp
> +                           "``float64`` vector of length 3: Coordindate of the "
Should be `Coordinate`

2024-02-01 16:53 UTC, mone27 commented on cpp/pybind/geometry/voxelgrid.cpp
> +                           "``float64`` vector of length 3: Coordindate of the "
ah sorry! should be fixed now

2024-02-27 05:01 UTC, ssheorey commented
Thanks @mone27 @saurabheights !

2024-02-27 05:01 UTC, ssheorey approved these changes

2024-02-27 05:01 UTC, merged