Implement t::geometry::TriangleMesh::RemoveUnreferencedVertices
isl-org/Open3D pull request #6640
Opened 2024-02-06 13:22 UTC by nsaiapova

The algorithm mimics the one in
geometry::TriangleMesh::RemoveUnreferencedVertices. We first build a mask of vertices and then update all vertex attributes by that mask. Triangles are left untouched.

## Type

-   [ ] Bug fix (non-breaking change which fixes an issue): Fixes #
-   [x] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context

Implement missing method t::geometry::TriangleMesh::RemoveUnreferencedVertices. The method is defined in the legacy API.

## Checklist:

-   [x] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [x] This PR changes Open3D behavior or adds new functionality.
    -   [x] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [x] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

## Description

2024-02-11 15:42 UTC, benjaminum requested changes

2024-02-20 13:30 UTC, nsaiapova commented on cpp/open3d/t/geometry/TriangleMesh.cpp
> +                "[RemoveUnreferencedVertices] TriangleMesh has no triangles.");
I hope I now have improved the corner cases handling. If we have vertices but no triangles, I keep the vertex mask empty and update all vertex attributes.

2024-02-27 04:50 UTC, ssheorey approved these changes
Looks good! Some minor comments.

2024-02-27 04:50 UTC, ssheorey commented on cpp/open3d/t/geometry/TriangleMesh.cpp
> +
nit: Add `LogDebug` message about how many vertices were removed.

2024-02-27 04:50 UTC, ssheorey commented on cpp/open3d/t/geometry/TriangleMesh.cpp
> +                "[RemoveUnreferencedVertices] TriangleMesh has no triangles.");
"[RemoveUnreferencedVertices] TriangleMesh has no triangles. Removing all vertices."

2024-03-05 15:45 UTC, benjaminum approved these changes

2024-03-18 21:11 UTC, merged