Implement ComputeTriangleAreas, GetNonManifoldEdges and RemoveNonManifoldEdges in t::geometry::TriangleMesh
isl-org/Open3D pull request #6657
Opened 2024-02-15 14:15 UTC by nsaiapova

Implement a few methods which are available with the geometry::TriangleMesh API.

## Type

-   [ ] Bug fix (non-breaking change which fixes an issue): Fixes #
-   [x] New feature (non-breaking change which adds functionality). Resolves #
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) Resolves #

## Motivation and Context

## Checklist:

-   [x] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code.
-   [x] This PR changes Open3D behavior or adds new functionality.
    -   [x] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [x] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.
    
-   [x] For fork PRs, I have selected **Allow edits from maintainers**.

## Description

In this PR three methods for t::geometry::TriangleMesh are implemented.

**t::geometry::TriangleMesh::ComputeTriangleAreas**
Split the logic from ComputeSurfaceArea into a helper static function
and introduce a new method which computes triangle areas and writes the
resulting tensor into attributes of the mesh.
IIUC, in geometry::TriangleMesh the corresponding function is GetSurfaceArea(std::vector &areas), where the areas are filled with the triangle areas.

**t::geometry::TriangleMesh::GetNonManifoldEdges** mimics the logic of the legacy method.

**t::geometry::TriangleMesh::RemoveNonManifoldEdges** follows the logic of
the legacy method but there are a few differences:
* the main difference is that the outer while-loop is removed. I don't
  see how after the first iteration any edge can have more than 2
  adjucent triangles, which makes the further iterations unnecessary.
* I count triangles with non-negative areas immediately and do not rely
  on the total number of adjacent triangles (which would also include
  triangles marked for removal).
* To choose a triangle with the minimal area out of the existing
  adjacent triangles I use a heap structure.

2024-02-26 16:57 UTC, benjaminum requested changes

2024-02-26 16:57 UTC, benjaminum commented on cpp/pybind/t/geometry/trianglemesh.cpp
> +    triangle_mesh.def("remove_non_manifold_edges",
Please add docstrings for python in the [google format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) similar to other functions in this file. Examples are optional but very welcome 😄

2024-03-05 06:51 UTC, ssheorey reviewed
Thanks @nsaiapova! Some minor comments. Feel free to ignore comments labeled with nit. We can chat about the algorithm....

2024-03-05 06:51 UTC, ssheorey commented on cpp/open3d/t/geometry/TriangleMesh.cpp
> +                non_manifold_edges.push_back(std::get<1>(kv.first));
nit: can do a single operation: `non_manifold_edges.insert(non_manifold_edges.end(), std::begin(kv.first), std::end(kv.first));`

2024-03-05 06:51 UTC, ssheorey commented on cpp/open3d/t/geometry/TriangleMesh.cpp
> +                auto area_greater_compare = [=](size_t lhs, size_t rhs) {
We only need to capture `tri_areas_ptr`:
`[=tri_areas_ptr](...) {...}`

2024-03-05 06:51 UTC, ssheorey commented on cpp/open3d/t/geometry/TriangleMesh.cpp
> +                // go through all edges and for those who has more than 2
typo: `...for those that have more...`

2024-03-05 06:51 UTC, ssheorey commented on cpp/open3d/t/geometry/TriangleMesh.cpp
> +                    std::make_heap(kv.second.begin(), kv.second.end(),
`std::nth_element` implements selection algorithm (i.e. select largest 2 elements in range) and we can use it directly.

2024-03-05 06:51 UTC, ssheorey commented on cpp/open3d/t/geometry/TriangleMesh.cpp
> +                    std::make_heap(kv.second.begin(), kv.second.end(),
We should be able to directly use `std::nt_element` after `std::remove_if` and simplify the code.

2024-03-05 06:51 UTC, ssheorey commented on cpp/open3d/t/geometry/TriangleMesh.cpp
> +    }
I think we should be able to support triangle uvs here. Perhaps just copy triangle uvs for the triangles that are retained?

2024-04-16 13:24 UTC, benjaminum commented on cpp/pybind/t/geometry/trianglemesh.cpp
> +                      "Compute triangle areas and save it as \"areas\" "
Just a suggestion. An example cold show how to access the new attribute and sum it to get the total surface area.

2024-04-16 13:24 UTC, benjaminum commented on python/test/t/geometry/test_trianglemesh.py
> +    torus = o3d.t.geometry.TriangleMesh.create_torus(2, 1, 6, 3, float_t, int_t,
Thanks for adding more unit tests

2024-04-28 21:49 UTC, ssheorey commented
Hi @nsaiapova can you take a look at the failing CI checks?
Looks like we are almost ready to merge after that.

2024-06-14 19:28 UTC, ssheorey approved these changes
Thanks @nsaiapova ! Looks good!

2024-06-15 20:11 UTC, merged