Fix #6725: O3DVisualizer: make points removable and fix point size calc
isl-org/Open3D pull request #6733
Opened 2024-03-29 10:29 UTC by danrauch

Correctly forward keymodifier to enable point removing and fix bounding box calculation for picked point size selection.

## Type

-   [x] Bug fix (non-breaking change which fixes an issue): Fixes #6725 
-   [ ] New feature (non-breaking change which adds functionality). 
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Motivation and Context

See issue

## Checklist:

-   [ ] I have run `python util/check_style.py --apply` to apply Open3D **code style**
    to my code. Have currently problems with this due to some pip problem
-   [ ] This PR changes Open3D behavior or adds new functionality.
    -   [ ] Both C++ (Doxygen) and Python (Sphinx / Google style) **documentation** is
        updated accordingly.
    -   [ ] I have added or updated C++ and / or Python **unit tests** OR included **test
        results** (e.g. screenshots or numbers) here.
-   [x] I will follow up and update the code if CI fails.

## Description

See issue

2024-04-16 13:33 UTC, errissa requested changes
Looks good other than the MacOS issue. Please resolve the CI failures and feel free to let me know if you need any help with it. Thank you for your contribution!

2024-04-16 13:33 UTC, errissa commented on cpp/open3d/visualization/visualizer/O3DVisualizer.cpp
> +        const char *selection_help = const char *selection_help =
This causes compilation error on MacOS

2024-04-17 11:11 UTC, danrauch commented on cpp/open3d/visualization/visualizer/O3DVisualizer.cpp
> +        const char *selection_help = const char *selection_help =
Fixed in c4d26f0

2024-04-17 18:54 UTC, ssheorey commented
Good to merge once CI passes. Thanks @danrauch for this useful bugfix.

2024-04-17 20:30 UTC, ssheorey approved these changes

2024-04-17 20:35 UTC, merged