add missing case RTC_ERROR_LEVEL_ZERO_RAYTRACING_SUPPORT_MISSING for …
isl-org/Open3D pull request #6901
Opened 2024-07-30 05:19 UTC by daizhirui

This pull request fixes the following build error:

```
Open3D/cpp/open3d/t/geometry/RaycastingScene.cpp:1184:9: error: enumeration value ‘RTC_ERROR_LEVEL_ZERO_RAYTRACING_SUPPORT_MISSING’ not handled in switch [-Werror=switch]
 1184 |         switch (c) {
      |         ^~~~~~
cc1plus: all warnings being treated as errors
```

2024-07-31 11:04 UTC, timohl commented
Failed with:
```/root/Open3D/cpp/open3d/t/geometry/RaycastingScene.cpp:1206:18: error: 'RTC_ERROR_LEVEL_ZERO_RAYTRACING_SUPPORT_MISSING' was not declared in this scope```

Did you build with another version of embree?

`enum RTCError` does not contain that value in my Ubuntu build of main at home : 
(`build/embree/src/ext_embree/include/embree4/rtcore_device.h:L79-L88`)
```python
enum RTCError
{
  RTC_ERROR_NONE              = 0,
  RTC_ERROR_UNKNOWN           = 1,
  RTC_ERROR_INVALID_ARGUMENT  = 2,
  RTC_ERROR_INVALID_OPERATION = 3,
  RTC_ERROR_OUT_OF_MEMORY     = 4,
  RTC_ERROR_UNSUPPORTED_CPU   = 5,
  RTC_ERROR_CANCELLED         = 6,
};
```

2024-07-31 11:10 UTC, timohl commented
Latest embree does contain the value though, so might be good when embree is upgraded:
https://github.com/RenderKit/embree/blob/3c9936cb6bfb21c572503438d7a10a432e885d2c/include/embree4/rtcore_device.h#L82-L92
```cpp
enum RTCError
{
  RTC_ERROR_NONE                                  = 0,
  RTC_ERROR_UNKNOWN                               = 1,
  RTC_ERROR_INVALID_ARGUMENT                      = 2,
  RTC_ERROR_INVALID_OPERATION                     = 3,
  RTC_ERROR_OUT_OF_MEMORY                         = 4,
  RTC_ERROR_UNSUPPORTED_CPU                       = 5,
  RTC_ERROR_CANCELLED                             = 6,
  RTC_ERROR_LEVEL_ZERO_RAYTRACING_SUPPORT_MISSING = 7,
};
```

2024-07-31 11:38 UTC, timohl requested changes
This change requires an upgraded embree version

If embree is upgraded, I would prefer using this function instead of switch case, in order to be independent of the actual enum values if future changes might occure:
https://github.com/RenderKit/embree/blob/3c9936cb6bfb21c572503438d7a10a432e885d2c/include/embree4/rtcore_device.h#L94C1-L95C60
```cpp
/* Returns the string representation for the error code. For example, for RTC_ERROR_UNKNOWN the string "RTC_ERROR_UNKNOWN" will be returned. */
RTC_API const char* rtcGetErrorString(enum RTCError error);
```

2024-07-31 12:39 UTC, daizhirui commented
@timohl I test it with embree `4.3.3`. A new commit is pushed according to your suggestion of using `rtcGetErrorString`.

2024-07-31 13:15 UTC, timohl requested changes
The additional enum value and `rtcGetErrorString` are actually new in [v4.3.3](https://github.com/RenderKit/embree/releases/tag/v4.3.3) which was released last week.

The main branch of open3D is on v4.3.1:
https://github.com/isl-org/Open3D/blob/f02e7d24ea115e716445a7fae5093bce60a37d20/3rdparty/embree/embree.cmake#L70-L71
See #6665 for the last pull request updating embree.

Maybe you could change the URL and URL_HASH to embree v4.3.3 as well, then the checks can run on the correct version.

2024-07-31 13:34 UTC, daizhirui commented
Okay, another commit is added to upgrade `embree`.

2024-07-31 14:09 UTC, timohl approved these changes
:LGTM:
Maybe update the title of this pull request and lets see how the checks go. :)

2024-08-14 17:25 UTC, ssheorey commented
Thanks @daizhirui for the PR and thanks @timohl for reviewing!

2024-08-14 17:26 UTC, merged